// @ts-nocheck
export function renderOverviewFinanceSection(financeOverview, helpers) {
    const { escapeHtml, formatMoney, formatDate, renderBadge, serializeJsonForScript } = helpers;
    if (!financeOverview) {
        return `<section class="panel overview-finance-panel" data-overview-finance-section><div class="panel-head"><h3>Finance outlook</h3></div><div class="panel-body"><div class="empty-state">Finance visibility appears after the company exists.</div></div></section>`;
    }
    const summaryCards = financeOverview.summaryCards
        .map((card) => `<article class="summary-item overview-finance-summary-card"><div class="eyebrow">${escapeHtml(card.label)}</div><strong>${escapeHtml(card.value)}</strong><div class="muted">${escapeHtml(card.detail)}</div></article>`)
        .join("");
    const categoryCards = financeOverview.categoryTotals
        .map((category) => `<article class="summary-item overview-finance-category-card"><div class="eyebrow">${escapeHtml(category.category)}</div><strong>${formatMoney(category.monthlyEquivalentAmount)}/mo</strong><div class="muted">${escapeHtml(category.detail)}</div></article>`)
        .join("");
    const visibleObligations = financeOverview.obligations.slice(0, 6);
    const hiddenObligationCount = Math.max(0, financeOverview.obligations.length - visibleObligations.length);
    const obligationList = visibleObligations.length === 0
        ? `<div class="empty-state compact">No active recurring obligations are visible.</div>`
        : `<div class="overview-finance-obligation-list">${visibleObligations
            .map((obligation) => `<article class="overview-finance-obligation ${escapeHtml(obligation.severity)}"><div class="meta-stack"><div class="overview-finance-obligation-head"><strong>${escapeHtml(obligation.label)}</strong><span>${formatMoney(obligation.amount)} ${escapeHtml(obligation.cadence)}</span></div><div class="muted">${escapeHtml(obligation.detail)}</div></div><div class="meta-stack"><span>${renderBadge(obligation.category)}</span><span class="muted">Due ${escapeHtml(formatDate(obligation.nextDueAtUtc))}</span></div></article>`).join("")}</div>`;
    const graphPayload = serializeJsonForScript(financeOverview.projection);
    return `<section class="panel overview-finance-panel" data-overview-finance-section tabindex="-1"><div class="panel-head"><h3>Finance outlook</h3><div class="pill-row"><span class="pill">${escapeHtml(String(financeOverview.obligations.length))} active obligations</span><span class="pill">${escapeHtml(String(financeOverview.projection.points.length))} projection points</span></div></div><div class="panel-body overview-finance-body"><div class="summary-list overview-finance-summary-strip">${summaryCards}</div><div class="view-grid two-up overview-finance-main-grid"><section class="aircraft-facts-card overview-finance-graph-panel"><div class="eyebrow">Projection</div><div class="overview-finance-graph-shell" data-overview-finance-graph><script type="application/json" data-overview-finance-graph-payload>${graphPayload}</script><div class="overview-finance-graph-toolbar"><div class="pill-row">${financeOverview.projection.horizons.map((horizon) => `<button type="button" class="ghost-button compact" data-finance-horizon="${escapeHtml(horizon.horizonId)}">${escapeHtml(horizon.label)}</button>`).join("")}</div><button type="button" class="ghost-button compact" data-finance-reset="1">Reset</button></div><div class="overview-finance-graph-frame"><svg viewBox="0 0 560 220" preserveAspectRatio="none" data-finance-graph-svg aria-label="Finance projection graph"></svg></div><div class="overview-finance-scrub-row"><input type="range" min="0" max="0" value="0" data-finance-scrub /><div class="summary-item compact overview-finance-scrub-summary" data-finance-point-summary><div class="eyebrow">Projection point</div><strong>Loading...</strong><div class="muted">Finance projection details appear here.</div></div></div></div></section><section class="aircraft-facts-card overview-finance-category-panel"><div class="eyebrow">Recurring categories</div><div class="summary-list overview-finance-category-grid">${categoryCards}</div><div class="muted overview-finance-category-note">Totals stay bounded to visible recurring obligations and accepted-work confidence layers only.</div></section></div><section class="aircraft-facts-card overview-finance-obligation-panel"><div class="panel-head"><h3>Obligation peek</h3>${hiddenObligationCount > 0 ? `<span class="muted">${escapeHtml(String(hiddenObligationCount))} more obligation${hiddenObligationCount === 1 ? "" : "s"} remain outside this peek.</span>` : ""}</div><div class="panel-body">${obligationList}</div></section></div></section>`;
}
