from __future__ import annotations

LAST_VERIFIED_ON = "2026-03-14"

SOURCE_REFS = {
    "msfs2024_su1_forum": "https://forums.flightsimulator.com/t/release-notes-microsoft-flight-simulator-2024-sim-update-1-1-3-23-0-available-now/709405",
    "msfs2024_su4": "https://www.flightsimulator.com/sim-update-4-msfs-2024/",
    "msfs2024_su4_early": "https://www.flightsimulator.com/release-notes-1-2-7-0-available-now-msfs-2024/",
    "msfs2024_manuals": "https://www.flightsimulator.com/aircraft-manuals/",
    "msfs_atr": "https://www.flightsimulator.com/expert-series-01-atr-42-600-72-600-expansion/",
    "msfs_atr_bundle": "https://www.flightsimulator.com/expert-series-i-atr-42-600-72-600/",
    "flybywire_a32nx": "https://docs.flybywiresim.com/release-notes/a32nx/v0140/",
    "headwind_home": "https://headwindsim.net/",
    "justflight_146": "https://www.justflight.com/product/146-professional-microsoft-flight-simulator",
    "inibuilds_a350": "https://inibuilds.com/products/inibuilds-a350-airliner-msfs-2024",
    "pmdg_737_900": "https://pmdg.com/pmdg-737-900-for-microsoft-flight-simulator-2020/",
}


def family(fid: str, name: str, manufacturer: str, qualification: str, mechanic: str, standardization: str, tags: list[str], notes: str) -> dict[str, object]:
    return {
        "family_id": fid,
        "display_name": name,
        "manufacturer": manufacturer,
        "qualification_group": qualification,
        "mechanic_group": mechanic,
        "standardization_group": standardization,
        "family_role_tags": tags,
        "notes": notes,
    }


def msfs_meta(status: str, available: bool, note: str, example_products: list[str], source_refs: list[str], *, included_tier: str = "", distribution_channels: list[str] | None = None) -> dict[str, object]:
    return {
        "msfs2024_available_for_user": available,
        "msfs2024_status": status,
        "msfs2024_included_tier": included_tier,
        "msfs2024_distribution_channels": distribution_channels or [],
        "msfs2024_example_products": example_products,
        "msfs2024_source_refs": source_refs,
        "msfs2024_user_note": note,
        "msfs2024_last_verified_on": LAST_VERIFIED_ON,
    }


def model(base: dict[str, object], meta: dict[str, object], model_id: str, family_id: str, display_name: str, short_name: str, variant_kind: str, in_service_role: str, max_passengers: int, max_cargo_lb: int, market_role_pool: str, best_fit_contract_tags: list[str], notes: str, **overrides: object) -> dict[str, object]:
    return base | meta | {
        "model_id": model_id,
        "family_id": family_id,
        "display_name": display_name,
        "short_name": short_name,
        "variant_kind": variant_kind,
        "in_service_role": in_service_role,
        "max_passengers": max_passengers,
        "max_cargo_lb": max_cargo_lb,
        "market_role_pool": market_role_pool,
        "best_fit_contract_tags": best_fit_contract_tags,
        "notes": notes,
    } | overrides


AVAILABLE_INCLUDED = "confirmed_available"
UNAVAILABLE = "confirmed_unavailable"
NOT_VERIFIED = "not_verified"

FAMILIES = [
    family("caravan", "Cessna 208 Caravan family", "Textron Aviation / Cessna", "single_turboprop_utility", "single_turboprop_pt6", "caravan_single", ["utility_passenger", "utility_cargo", "remote_utility"], "Flexible early-game utility single for cargo and thin passenger work."),
    family("skycourier", "Cessna 408 SkyCourier family", "Textron Aviation / Cessna", "twin_turboprop_utility", "twin_turboprop_pt6", "skycourier", ["utility_cargo", "utility_passenger", "short_field"], "Utility twin focused on scalable feeder cargo and small-community service."),
    family("pc12", "Pilatus PC-12 family", "Pilatus", "single_turboprop_premium", "single_turboprop_pt6", "pc12", ["premium_charter", "executive", "urgent"], "Premium single-turboprop lane for charter and high-value contracts."),
    family("twin_otter", "DHC-6 Twin Otter family", "De Havilland Canada", "twin_turboprop_utility", "twin_turboprop_pt6", "twin_otter", ["rugged_remote_field", "remote_utility", "short_field"], "Remote-ops specialist with strong rough-field and short-field access."),
    family("saab340", "Saab 340 family", "Saab", "twin_turboprop_commuter", "twin_turboprop_commuter", "saab340", ["commuter_passenger", "thin_regional", "feeder"], "Entry commuter twin for thin scheduled regional passenger work."),
    family("atr", "ATR 42/72 family", "ATR / Hans Hartmann", "regional_turboprop", "regional_turboprop", "atr", ["regional_passenger", "regional_cargo", "combi"], "Core mid-game turboprop backbone for feeder passenger and freight lanes."),
    family("citation_cj", "Citation CJ family", "Textron Aviation / Cessna", "light_business_jet", "light_business_jet", "citation_cj", ["premium_charter", "executive", "urgent"], "Fast premium-charter lane with low seat count and high revenue urgency."),
    family("pc24", "Pilatus PC-24 family", "Pilatus", "light_business_jet", "light_business_jet", "pc24", ["premium_charter", "short_field_jet", "urgent"], "Premium jet with unusually strong runway flexibility."),
    family("a320neo", "Airbus A320neo family", "Airbus / iniBuilds / FlyByWire", "narrowbody_airline", "narrowbody_airline", "airbus_narrowbody", ["narrowbody_passenger", "network_scale", "trunk_routes"], "Primary Airbus narrowbody lane for network growth and dense passenger work."),
    family("b737", "Boeing 737 family", "Boeing / Asobo / PMDG", "narrowbody_airline", "narrowbody_airline", "boeing_737", ["narrowbody_passenger", "network_scale", "trunk_routes"], "Boeing narrowbody lane with mixed MSFS availability depending on the exact variant."),
    family("a330", "Airbus A330 family", "Airbus / iniBuilds / Headwind Simulations", "widebody_airline", "widebody_airline", "airbus_widebody", ["widebody_passenger", "long_haul", "heavy_cargo"], "Widebody lane for long-haul and high-capacity premium network play."),
    family("bae146", "BAe 146 family", "British Aerospace / Just Flight", "regional_jet_classic", "regional_jet_classic", "bae146", ["regional_passenger", "regional_cargo", "short_field_jet"], "Classic quiet regional jet family with distinct cargo and city-airport use cases."),
    family("a350", "Airbus A350 family", "Airbus / iniBuilds", "widebody_airline", "widebody_airline", "airbus_widebody_next", ["widebody_passenger", "flagship", "long_haul"], "Flagship late-game widebody lane for premium long-haul expansion."),
    family("beech1900", "Beechcraft 1900 family", "Beechcraft", "twin_turboprop_commuter", "twin_turboprop_commuter", "beech1900", ["commuter_passenger", "thin_regional"], "Kept as an unverified reference candidate for later roster expansion."),
    family("jetstream32", "Jetstream 32 family", "British Aerospace / Jetstream", "twin_turboprop_commuter", "twin_turboprop_commuter", "jetstream32", ["commuter_passenger", "thin_regional"], "Kept as an unverified reference candidate for later roster expansion."),
]

BASE_UTILITY_SINGLE = {"aircraft_category": "single_turboprop", "engine_type": "turboprop", "fuel_type": "jet_a", "pressurized": False, "payload_class": "light", "combi_capable": False, "cruise_speed_ktas": 182, "range_nm": 900, "fuel_burn_gph": 72.0, "typical_turnaround_min": 30, "minimum_runway_ft": 2200, "preferred_runway_ft": 3000, "hard_surface_required": False, "rough_field_capable": True, "market_value_usd": 2200000, "target_lease_rate_monthly_usd": 38000, "variable_operating_cost_per_hour_usd": 550, "fixed_support_cost_per_day_usd": 220, "maintenance_reserve_per_hour_usd": 140, "pilot_qualification_group": "single_turboprop_utility", "pilots_required": 1, "flight_attendants_required": 0, "mechanic_skill_group": "single_turboprop_pt6", "base_dispatch_reliability": 0.965, "condition_decay_per_hour": 0.0050, "condition_decay_per_cycle": 0.0800, "inspection_interval_hours": 120, "inspection_interval_cycles": 90, "heavy_maintenance_band": "light_turboprop", "maintenance_downtime_hours": 36, "progression_tier": 1, "startup_eligible": True, "reputation_gate": 0, "airport_access_profile": "short_rough_friendly", "data_confidence": "starter_design_band"}
BASE_UTILITY_TWIN = {"aircraft_category": "twin_turboprop", "engine_type": "turboprop", "fuel_type": "jet_a", "pressurized": True, "payload_class": "medium", "combi_capable": False, "cruise_speed_ktas": 205, "range_nm": 900, "fuel_burn_gph": 165.0, "typical_turnaround_min": 35, "minimum_runway_ft": 2600, "preferred_runway_ft": 3600, "hard_surface_required": False, "rough_field_capable": True, "market_value_usd": 4700000, "target_lease_rate_monthly_usd": 78000, "variable_operating_cost_per_hour_usd": 920, "fixed_support_cost_per_day_usd": 360, "maintenance_reserve_per_hour_usd": 280, "pilot_qualification_group": "twin_turboprop_utility", "pilots_required": 2, "flight_attendants_required": 0, "mechanic_skill_group": "twin_turboprop_pt6", "base_dispatch_reliability": 0.952, "condition_decay_per_hour": 0.0065, "condition_decay_per_cycle": 0.1100, "inspection_interval_hours": 110, "inspection_interval_cycles": 95, "heavy_maintenance_band": "utility_twin_turboprop", "maintenance_downtime_hours": 48, "progression_tier": 2, "startup_eligible": True, "reputation_gate": 6, "airport_access_profile": "remote_twin_capable", "data_confidence": "starter_design_band"}
BASE_PREMIUM_SINGLE = {"aircraft_category": "single_turboprop", "engine_type": "turboprop", "fuel_type": "jet_a", "pressurized": True, "payload_class": "light", "combi_capable": False, "cruise_speed_ktas": 285, "range_nm": 1600, "fuel_burn_gph": 82.0, "typical_turnaround_min": 25, "minimum_runway_ft": 2600, "preferred_runway_ft": 3400, "hard_surface_required": False, "rough_field_capable": False, "market_value_usd": 5400000, "target_lease_rate_monthly_usd": 90000, "variable_operating_cost_per_hour_usd": 780, "fixed_support_cost_per_day_usd": 320, "maintenance_reserve_per_hour_usd": 220, "pilot_qualification_group": "single_turboprop_premium", "pilots_required": 1, "flight_attendants_required": 0, "mechanic_skill_group": "single_turboprop_pt6", "base_dispatch_reliability": 0.972, "condition_decay_per_hour": 0.0044, "condition_decay_per_cycle": 0.0700, "inspection_interval_hours": 130, "inspection_interval_cycles": 100, "heavy_maintenance_band": "premium_single_turboprop", "maintenance_downtime_hours": 42, "progression_tier": 2, "startup_eligible": True, "reputation_gate": 10, "airport_access_profile": "premium_short_field", "data_confidence": "starter_design_band"}
BASE_COMMUTER_TWIN = {"aircraft_category": "twin_turboprop", "engine_type": "turboprop", "fuel_type": "jet_a", "pressurized": True, "payload_class": "medium", "combi_capable": False, "cruise_speed_ktas": 282, "range_nm": 900, "fuel_burn_gph": 210.0, "typical_turnaround_min": 40, "minimum_runway_ft": 3600, "preferred_runway_ft": 4500, "hard_surface_required": True, "rough_field_capable": False, "market_value_usd": 6200000, "target_lease_rate_monthly_usd": 105000, "variable_operating_cost_per_hour_usd": 1200, "fixed_support_cost_per_day_usd": 480, "maintenance_reserve_per_hour_usd": 350, "pilot_qualification_group": "twin_turboprop_commuter", "pilots_required": 2, "flight_attendants_required": 1, "mechanic_skill_group": "twin_turboprop_commuter", "base_dispatch_reliability": 0.950, "condition_decay_per_hour": 0.0068, "condition_decay_per_cycle": 0.1200, "inspection_interval_hours": 105, "inspection_interval_cycles": 110, "heavy_maintenance_band": "commuter_turboprop", "maintenance_downtime_hours": 54, "progression_tier": 3, "startup_eligible": False, "reputation_gate": 18, "airport_access_profile": "regional_paved", "data_confidence": "starter_design_band"}
BASE_REGIONAL_TURBOPROP = {"aircraft_category": "regional_turboprop", "engine_type": "turboprop", "fuel_type": "jet_a", "pressurized": True, "payload_class": "regional", "combi_capable": True, "cruise_speed_ktas": 302, "range_nm": 850, "fuel_burn_gph": 275.0, "typical_turnaround_min": 48, "minimum_runway_ft": 3950, "preferred_runway_ft": 5200, "hard_surface_required": True, "rough_field_capable": False, "market_value_usd": 13800000, "target_lease_rate_monthly_usd": 235000, "variable_operating_cost_per_hour_usd": 2000, "fixed_support_cost_per_day_usd": 760, "maintenance_reserve_per_hour_usd": 560, "pilot_qualification_group": "regional_turboprop", "pilots_required": 2, "flight_attendants_required": 1, "mechanic_skill_group": "regional_turboprop", "base_dispatch_reliability": 0.944, "condition_decay_per_hour": 0.0078, "condition_decay_per_cycle": 0.1400, "inspection_interval_hours": 100, "inspection_interval_cycles": 130, "heavy_maintenance_band": "regional_turboprop", "maintenance_downtime_hours": 60, "progression_tier": 4, "startup_eligible": False, "reputation_gate": 28, "airport_access_profile": "regional_paved", "data_confidence": "starter_design_band"}
BASE_BUSINESS_JET = {"aircraft_category": "business_jet", "engine_type": "turbofan", "fuel_type": "jet_a", "pressurized": True, "payload_class": "light", "combi_capable": False, "cruise_speed_ktas": 430, "range_nm": 1900, "fuel_burn_gph": 195.0, "typical_turnaround_min": 28, "minimum_runway_ft": 3400, "preferred_runway_ft": 4300, "hard_surface_required": True, "rough_field_capable": False, "market_value_usd": 10400000, "target_lease_rate_monthly_usd": 180000, "variable_operating_cost_per_hour_usd": 1750, "fixed_support_cost_per_day_usd": 580, "maintenance_reserve_per_hour_usd": 430, "pilot_qualification_group": "light_business_jet", "pilots_required": 1, "flight_attendants_required": 0, "mechanic_skill_group": "light_business_jet", "base_dispatch_reliability": 0.968, "condition_decay_per_hour": 0.0052, "condition_decay_per_cycle": 0.0750, "inspection_interval_hours": 140, "inspection_interval_cycles": 120, "heavy_maintenance_band": "light_business_jet", "maintenance_downtime_hours": 52, "progression_tier": 4, "startup_eligible": False, "reputation_gate": 24, "airport_access_profile": "premium_paved", "data_confidence": "starter_design_band"}
BASE_NARROWBODY = {"aircraft_category": "narrowbody_airliner", "engine_type": "turbofan", "fuel_type": "jet_a", "pressurized": True, "payload_class": "airliner", "combi_capable": False, "cruise_speed_ktas": 452, "range_nm": 3400, "fuel_burn_gph": 710.0, "typical_turnaround_min": 70, "minimum_runway_ft": 6500, "preferred_runway_ft": 8000, "hard_surface_required": True, "rough_field_capable": False, "market_value_usd": 54000000, "target_lease_rate_monthly_usd": 790000, "variable_operating_cost_per_hour_usd": 6800, "fixed_support_cost_per_day_usd": 2750, "maintenance_reserve_per_hour_usd": 2200, "pilot_qualification_group": "narrowbody_airline", "pilots_required": 2, "flight_attendants_required": 4, "mechanic_skill_group": "narrowbody_airline", "base_dispatch_reliability": 0.942, "condition_decay_per_hour": 0.0085, "condition_decay_per_cycle": 0.0900, "inspection_interval_hours": 220, "inspection_interval_cycles": 180, "heavy_maintenance_band": "narrowbody_airliner", "maintenance_downtime_hours": 84, "progression_tier": 6, "startup_eligible": False, "reputation_gate": 52, "airport_access_profile": "mainline_paved", "data_confidence": "starter_design_band"}
BASE_WIDEBODY = {"aircraft_category": "widebody_airliner", "engine_type": "turbofan", "fuel_type": "jet_a", "pressurized": True, "payload_class": "heavy", "combi_capable": False, "cruise_speed_ktas": 472, "range_nm": 6400, "fuel_burn_gph": 1450.0, "typical_turnaround_min": 100, "minimum_runway_ft": 8200, "preferred_runway_ft": 9800, "hard_surface_required": True, "rough_field_capable": False, "market_value_usd": 118000000, "target_lease_rate_monthly_usd": 1700000, "variable_operating_cost_per_hour_usd": 12800, "fixed_support_cost_per_day_usd": 4900, "maintenance_reserve_per_hour_usd": 4100, "pilot_qualification_group": "widebody_airline", "pilots_required": 2, "flight_attendants_required": 8, "mechanic_skill_group": "widebody_airline", "base_dispatch_reliability": 0.936, "condition_decay_per_hour": 0.0096, "condition_decay_per_cycle": 0.1100, "inspection_interval_hours": 260, "inspection_interval_cycles": 200, "heavy_maintenance_band": "widebody_airliner", "maintenance_downtime_hours": 120, "progression_tier": 7, "startup_eligible": False, "reputation_gate": 68, "airport_access_profile": "widebody_paved", "data_confidence": "starter_design_band"}
BASE_CLASSIC_REGIONAL_JET = {"aircraft_category": "regional_jet", "engine_type": "turbofan", "fuel_type": "jet_a", "pressurized": True, "payload_class": "regional", "combi_capable": False, "cruise_speed_ktas": 392, "range_nm": 1100, "fuel_burn_gph": 920.0, "typical_turnaround_min": 52, "minimum_runway_ft": 4500, "preferred_runway_ft": 6000, "hard_surface_required": True, "rough_field_capable": False, "market_value_usd": 14000000, "target_lease_rate_monthly_usd": 230000, "variable_operating_cost_per_hour_usd": 3100, "fixed_support_cost_per_day_usd": 900, "maintenance_reserve_per_hour_usd": 850, "pilot_qualification_group": "regional_jet_classic", "pilots_required": 2, "flight_attendants_required": 1, "mechanic_skill_group": "regional_jet_classic", "base_dispatch_reliability": 0.939, "condition_decay_per_hour": 0.0089, "condition_decay_per_cycle": 0.1000, "inspection_interval_hours": 180, "inspection_interval_cycles": 160, "heavy_maintenance_band": "regional_jet_classic", "maintenance_downtime_hours": 96, "progression_tier": 5, "startup_eligible": False, "reputation_gate": 40, "airport_access_profile": "regional_jet_paved", "data_confidence": "starter_design_band"}
BASE_NOT_VERIFIED_COMMUTER = {"aircraft_category": "twin_turboprop", "engine_type": "turboprop", "fuel_type": "jet_a", "pressurized": True, "payload_class": "medium", "combi_capable": False, "cruise_speed_ktas": 255, "range_nm": 850, "fuel_burn_gph": 155.0, "typical_turnaround_min": 35, "minimum_runway_ft": 3500, "preferred_runway_ft": 4300, "hard_surface_required": True, "rough_field_capable": False, "market_value_usd": 2700000, "target_lease_rate_monthly_usd": 44000, "variable_operating_cost_per_hour_usd": 920, "fixed_support_cost_per_day_usd": 360, "maintenance_reserve_per_hour_usd": 240, "pilot_qualification_group": "twin_turboprop_commuter", "pilots_required": 2, "flight_attendants_required": 0, "mechanic_skill_group": "twin_turboprop_commuter", "base_dispatch_reliability": 0.944, "condition_decay_per_hour": 0.0070, "condition_decay_per_cycle": 0.1200, "inspection_interval_hours": 105, "inspection_interval_cycles": 110, "heavy_maintenance_band": "commuter_turboprop", "maintenance_downtime_hours": 48, "progression_tier": 2, "startup_eligible": False, "reputation_gate": 12, "airport_access_profile": "regional_paved", "data_confidence": "starter_design_band"}

MODELS = [
    model(BASE_UTILITY_SINGLE, msfs_meta(AVAILABLE_INCLUDED, True, "Confirmed as a current first-party MSFS 2024 aircraft in the official Sim Update 1 release notes.", ["Cessna 208 B Grand Caravan EX"], [SOURCE_REFS["msfs2024_su1_forum"]], included_tier="included", distribution_channels=["included_first_party"]), "cessna_208b_grand_caravan_ex_passenger", "caravan", "Cessna 208 B Grand Caravan EX Passenger", "Caravan Passenger", "passenger", "Utility passenger turboprop", 10, 1600, "utility_passenger", ["regional_passenger", "thin_passenger", "remote_utility"], "Passenger-leaning Caravan variant for thin routes and small-community work."),
    model(BASE_UTILITY_SINGLE, msfs_meta(AVAILABLE_INCLUDED, True, "Confirmed as a current first-party MSFS 2024 aircraft in the official Sim Update 1 release notes.", ["Cessna 208 B Grand Caravan EX"], [SOURCE_REFS["msfs2024_su1_forum"]], included_tier="included", distribution_channels=["included_first_party"]), "cessna_208b_grand_caravan_ex_cargo", "caravan", "Cessna 208 B Grand Caravan EX Cargo", "Caravan Cargo", "cargo", "Utility cargo turboprop", 0, 3300, "utility_cargo", ["light_cargo", "remote_cargo", "ad_hoc"], "Cargo-configured Caravan that keeps startup freight viable."),
    model(BASE_UTILITY_TWIN, msfs_meta(AVAILABLE_INCLUDED, True, "Confirmed as a current first-party MSFS 2024 aircraft in official release notes.", ["Cessna 408 SkyCourier"], [SOURCE_REFS["msfs2024_su1_forum"], SOURCE_REFS["msfs2024_su4"]], included_tier="included", distribution_channels=["included_first_party"]), "cessna_408_skycourier_freighter", "skycourier", "Cessna 408 SkyCourier Freighter", "SkyCourier F", "cargo", "Utility feeder freighter", 0, 6200, "utility_cargo", ["medium_cargo", "scheduled_cargo", "remote_cargo"], "Feeder cargo twin that expands payload without jumping to ATR-class costs.", cruise_speed_ktas=210, market_value_usd=5200000, target_lease_rate_monthly_usd=86000, variable_operating_cost_per_hour_usd=980, maintenance_reserve_per_hour_usd=300),
    model(BASE_PREMIUM_SINGLE, msfs_meta(AVAILABLE_INCLUDED, True, "Confirmed as a current first-party MSFS 2024 aircraft in the official Sim Update 4 release notes.", ["Pilatus PC-12 NGX"], [SOURCE_REFS["msfs2024_su4"]], included_tier="included", distribution_channels=["included_first_party"]), "pilatus_pc12_ngx", "pc12", "Pilatus PC-12 NGX", "PC-12 NGX", "executive", "Premium charter single turboprop", 8, 1800, "premium_charter", ["vip_charter", "urgent_charter", "premium_regional"], "High-margin single-engine charter aircraft for premium small-company play."),
    model(BASE_UTILITY_TWIN, msfs_meta(AVAILABLE_INCLUDED, True, "Confirmed on the official MSFS aircraft manuals page as a current MSFS 2024 aircraft.", ["DHC-6 Twin Otter"], [SOURCE_REFS["msfs2024_manuals"]], included_tier="included", distribution_channels=["included_first_party"]), "dhc6_twin_otter_300", "twin_otter", "DHC-6 Twin Otter 300", "Twin Otter", "passenger_combi", "Rugged remote-field twin turboprop", 19, 4200, "rugged_remote_field", ["remote_passenger", "remote_cargo", "short_field"], "Remote access specialist for constrained strips and hard-to-serve airports.", combi_capable=True, cruise_speed_ktas=170, range_nm=760, fuel_burn_gph=120.0, typical_turnaround_min=38, minimum_runway_ft=1500, preferred_runway_ft=2200, market_value_usd=4800000, target_lease_rate_monthly_usd=82000, variable_operating_cost_per_hour_usd=870),
    model(BASE_COMMUTER_TWIN, msfs_meta(AVAILABLE_INCLUDED, True, "Confirmed as a current first-party MSFS 2024 aircraft in the official Sim Update 4 release notes.", ["Saab 340B"], [SOURCE_REFS["msfs2024_su4"]], included_tier="included", distribution_channels=["included_first_party"]), "saab_340b", "saab340", "Saab 340B", "Saab 340B", "passenger", "Commuter turboprop airliner", 34, 2200, "commuter_passenger", ["regional_passenger", "feeder", "thin_scheduled"], "Classic commuter twin for early regional network building."),
    model(BASE_REGIONAL_TURBOPROP, msfs_meta(AVAILABLE_INCLUDED, True, "Available to MSFS users through the official ATR package and current Content Manager support.", ["Expert Series 01: ATR 42-600 / 72-600"], [SOURCE_REFS["msfs_atr"], SOURCE_REFS["msfs_atr_bundle"]], included_tier="owned_addon", distribution_channels=["official_content_manager_addon"]), "atr_42_600_combi", "atr", "ATR 42-600 Combi", "ATR 42 Combi", "combi", "Regional turboprop combi", 42, 8000, "regional_passenger", ["regional_passenger", "combi", "feeder"], "Balanced feeder aircraft that keeps both passenger and freight options open.", market_value_usd=12800000, target_lease_rate_monthly_usd=220000, variable_operating_cost_per_hour_usd=1900, maintenance_reserve_per_hour_usd=520),
    model(BASE_REGIONAL_TURBOPROP, msfs_meta(AVAILABLE_INCLUDED, True, "Available to MSFS users through the official ATR package, including the 72-600F freighter update.", ["Expert Series 01: ATR 42-600 / 72-600", "ATR 72-600F"], [SOURCE_REFS["msfs_atr"], SOURCE_REFS["msfs_atr_bundle"]], included_tier="owned_addon", distribution_channels=["official_content_manager_addon"]), "atr_72_600f", "atr", "ATR 72-600F", "ATR 72F", "cargo", "Regional feeder freighter", 0, 17000, "regional_cargo_combi", ["scheduled_cargo", "feeder_cargo", "dense_regional"], "Dedicated regional freight aircraft for denser cargo boards.", combi_capable=False, range_nm=900, fuel_burn_gph=305.0, typical_turnaround_min=55, minimum_runway_ft=4300, preferred_runway_ft=5600, market_value_usd=15000000, target_lease_rate_monthly_usd=260000, variable_operating_cost_per_hour_usd=2200, fixed_support_cost_per_day_usd=820, maintenance_reserve_per_hour_usd=600, flight_attendants_required=0),
    model(BASE_BUSINESS_JET, msfs_meta(AVAILABLE_INCLUDED, True, "Confirmed in official MSFS 2024 documentation and current release notes as a first-party aircraft.", ["Cessna Citation CJ4"], [SOURCE_REFS["msfs2024_manuals"], SOURCE_REFS["msfs2024_su4"]], included_tier="included", distribution_channels=["included_first_party"]), "cessna_citation_cj4", "citation_cj", "Cessna Citation CJ4", "Citation CJ4", "executive", "Light business jet", 8, 1000, "premium_charter", ["vip_charter", "urgent_charter", "executive"], "Speed-driven charter aircraft with low seat count and high schedule value."),
    model(BASE_BUSINESS_JET, msfs_meta(AVAILABLE_INCLUDED, True, "Confirmed as a current first-party MSFS 2024 aircraft in official release notes.", ["Pilatus PC-24"], [SOURCE_REFS["msfs2024_su4"], SOURCE_REFS["msfs2024_su4_early"]], included_tier="included", distribution_channels=["included_first_party"]), "pilatus_pc24", "pc24", "Pilatus PC-24", "PC-24", "executive", "Short-field capable business jet", 8, 2300, "premium_charter", ["vip_charter", "urgent_charter", "short_field_jet"], "Premium jet that reaches faster missions without fully surrendering runway flexibility.", minimum_runway_ft=2800, preferred_runway_ft=3800, rough_field_capable=True, market_value_usd=11700000, target_lease_rate_monthly_usd=200000, variable_operating_cost_per_hour_usd=1850, fixed_support_cost_per_day_usd=620, maintenance_reserve_per_hour_usd=460),
    model(BASE_NARROWBODY, msfs_meta(AVAILABLE_INCLUDED, True, "Built into MSFS 2024 and also represented on PC by the officially compatible FlyByWire A32NX.", ["Airbus A320neo V2", "FlyByWire A32NX"], [SOURCE_REFS["msfs2024_manuals"], SOURCE_REFS["flybywire_a32nx"]], included_tier="included", distribution_channels=["included_first_party", "third_party_freeware"]), "airbus_a320neo", "a320neo", "Airbus A320neo", "A320neo", "passenger", "Narrowbody passenger airliner", 180, 43000, "aspirational_stretch", ["trunk_passenger", "dense_regional", "scheduled_passenger"], "Core Airbus narrowbody entry for dense scheduled passenger expansion."),
    model(BASE_NARROWBODY, msfs_meta(AVAILABLE_INCLUDED, True, "Confirmed as a current first-party MSFS 2024 aircraft in the official 1.2.7.0 release notes.", ["Boeing 737 MAX 8"], [SOURCE_REFS["msfs2024_su4_early"]], included_tier="included", distribution_channels=["included_first_party"]), "boeing_737_max_8", "b737", "Boeing 737 MAX 8", "737 MAX 8", "passenger", "Narrowbody passenger airliner", 189, 46000, "aspirational_stretch", ["trunk_passenger", "scheduled_passenger", "network_scale"], "Core Boeing narrowbody option for dense passenger growth.", market_value_usd=56000000, target_lease_rate_monthly_usd=820000, variable_operating_cost_per_hour_usd=6900, maintenance_reserve_per_hour_usd=2300),
    model(BASE_NARROWBODY, msfs_meta(UNAVAILABLE, False, "The current PMDG product page warns that this 737-900 package is not compatible with MSFS 2024.", ["PMDG 737-900", "PMDG 737-900ER"], [SOURCE_REFS["pmdg_737_900"]], distribution_channels=["third_party_paid"]), "boeing_737_900er", "b737", "Boeing 737-900ER", "737-900ER", "passenger", "Narrowbody stretch airliner", 215, 47000, "aspirational_stretch", ["trunk_passenger", "scheduled_passenger", "network_scale"], "Stored as a real roster candidate, but currently marked unavailable to the user in MSFS 2024.", range_nm=3200, market_value_usd=52000000, target_lease_rate_monthly_usd=770000, variable_operating_cost_per_hour_usd=7000, fixed_support_cost_per_day_usd=2820, maintenance_reserve_per_hour_usd=2320),
    model(BASE_WIDEBODY, msfs_meta(AVAILABLE_INCLUDED, True, "Confirmed in official MSFS 2024 documentation and release notes as a current first-party aircraft.", ["Airbus A330-300"], [SOURCE_REFS["msfs2024_manuals"], SOURCE_REFS["msfs2024_su4"]], included_tier="included", distribution_channels=["included_first_party"]), "airbus_a330_300", "a330", "Airbus A330-300", "A330-300", "passenger", "Widebody passenger airliner", 290, 70000, "aspirational_stretch", ["longhaul_passenger", "heavy_passenger", "hub_spoke"], "First-party A330 anchor for widebody progression.", range_nm=6100, fuel_burn_gph=1480.0, market_value_usd=105000000, target_lease_rate_monthly_usd=1500000, variable_operating_cost_per_hour_usd=12000, fixed_support_cost_per_day_usd=4500, maintenance_reserve_per_hour_usd=3800),
    model(BASE_WIDEBODY, msfs_meta(AVAILABLE_INCLUDED, True, "Confirmed as a freeware add-on for Microsoft Flight Simulator on the official Headwind Simulations site.", ["Headwind Simulations A339X"], [SOURCE_REFS["headwind_home"]], distribution_channels=["third_party_freeware"]), "airbus_a330_900neo", "a330", "Airbus A330-900neo", "A330-900neo", "passenger", "Widebody passenger airliner", 300, 72000, "aspirational_stretch", ["longhaul_passenger", "heavy_passenger", "hub_spoke"], "Freeware long-haul A330neo path for users who want a current PC add-on overlap.", range_nm=6500, market_value_usd=118000000, target_lease_rate_monthly_usd=1650000),
    model(BASE_CLASSIC_REGIONAL_JET, msfs_meta(AVAILABLE_INCLUDED, True, "Confirmed on the official Just Flight product page as compatible with MSFS 2024 and 2020.", ["Just Flight 146 Professional"], [SOURCE_REFS["justflight_146"]], distribution_channels=["third_party_paid", "marketplace_paid"]), "bae_146_200_qt", "bae146", "BAe 146-200 QT", "146-200 QT", "cargo", "Quiet regional freighter", 0, 26000, "regional_cargo_combi", ["night_cargo", "regional_cargo", "short_field_jet"], "Distinct late-midgame regional freighter with strong city-airport identity.", combi_capable=False, flight_attendants_required=0),
    model(BASE_WIDEBODY, msfs_meta(AVAILABLE_INCLUDED, True, "Confirmed on the official iniBuilds store as an MSFS 2024 product.", ["iniBuilds A350 Airliner"], [SOURCE_REFS["inibuilds_a350"]], distribution_channels=["third_party_paid"]), "airbus_a350_900", "a350", "Airbus A350-900", "A350-900", "passenger", "Flagship widebody airliner", 325, 80000, "aspirational_stretch", ["flagship_passenger", "longhaul_passenger", "premium_longhaul"], "Late-game flagship passenger aircraft with the heaviest prestige and capital burden in the starter set.", cruise_speed_ktas=488, range_nm=8200, fuel_burn_gph=1520.0, typical_turnaround_min=110, minimum_runway_ft=9000, preferred_runway_ft=10500, market_value_usd=165000000, target_lease_rate_monthly_usd=2400000, variable_operating_cost_per_hour_usd=16000, fixed_support_cost_per_day_usd=6500, maintenance_reserve_per_hour_usd=5200, progression_tier=8, reputation_gate=80),
    model(BASE_NOT_VERIFIED_COMMUTER, msfs_meta(NOT_VERIFIED, False, "No current official MSFS 2024 availability path has been confirmed in FlightLine's source set. Treat this aircraft as not currently available to the user until verified.", [], []), "beechcraft_1900d", "beech1900", "Beechcraft 1900D", "Beech 1900D", "passenger", "Commuter turboprop airliner", 19, 2000, "commuter_passenger", ["thin_scheduled", "regional_passenger", "feeder"], "Useful future commuter candidate kept visible as a not-yet-verified MSFS overlap.", cruise_speed_ktas=275),
    model(BASE_NOT_VERIFIED_COMMUTER, msfs_meta(NOT_VERIFIED, False, "No current official MSFS 2024 availability path has been confirmed in FlightLine's source set. Treat this aircraft as not currently available to the user until verified.", [], []), "jetstream_32", "jetstream32", "Jetstream 32", "Jetstream 32", "passenger", "Commuter turboprop airliner", 19, 1800, "commuter_passenger", ["thin_scheduled", "regional_passenger", "feeder"], "Useful future commuter candidate kept visible as a not-yet-verified MSFS overlap.", cruise_speed_ktas=245, fuel_burn_gph=170.0),
]
