from __future__ import annotations

LAST_VERIFIED_ON = "2026-03-14"
DEFAULT_NOT_VERIFIED_NOTE = (
    "FlightLine has not yet confirmed a current MSFS 2024 availability path for this aircraft. "
    "The aircraft is still fully eligible for acquisition in FlightLine."
)

SOURCE_REFS = {
    "msfs2024_su1_forum": "https://forums.flightsimulator.com/t/release-notes-microsoft-flight-simulator-2024-sim-update-1-1-3-23-0-available-now/709405",
    "msfs2024_su4": "https://www.flightsimulator.com/sim-update-4-msfs-2024/",
    "msfs2024_su4_early": "https://www.flightsimulator.com/release-notes-1-2-7-0-available-now-msfs-2024/",
    "msfs2024_manuals": "https://www.flightsimulator.com/aircraft-manuals/",
    "msfs_atr": "https://www.flightsimulator.com/expert-series-01-atr-42-600-72-600-expansion/",
    "msfs_atr_bundle": "https://www.flightsimulator.com/expert-series-i-atr-42-600-72-600/",
    "flybywire_a32nx": "https://docs.flybywiresim.com/release-notes/a32nx/v0140/",
    "headwind_home": "https://headwindsim.net/",
    "justflight_146": "https://www.justflight.com/product/146-professional-microsoft-flight-simulator",
    "justflight_f28": "https://www.justflight.com/product/f28-professional",
    "justflight_rj": "https://www.justflight.com/product/rj-professional-msfs",
    "inibuilds_a350": "https://inibuilds.com/products/inibuilds-a350-airliner-msfs-2024",
    "pmdg_737_900": "https://pmdg.com/pmdg-737-900-for-microsoft-flight-simulator-2020/",
}


def family(fid: str, name: str, manufacturer: str, qualification: str, mechanic: str, standardization: str, tags: list[str], notes: str) -> dict[str, object]:
    return {
        "family_id": fid,
        "display_name": name,
        "manufacturer": manufacturer,
        "qualification_group": qualification,
        "mechanic_group": mechanic,
        "standardization_group": standardization,
        "family_role_tags": tags,
        "notes": notes,
    }


def msfs_meta(status: str, available: bool, note: str, example_products: list[str], source_refs: list[str], *, included_tier: str = "", distribution_channels: list[str] | None = None) -> dict[str, object]:
    return {
        "msfs2024_available_for_user": available,
        "msfs2024_status": status,
        "msfs2024_included_tier": included_tier,
        "msfs2024_distribution_channels": distribution_channels or [],
        "msfs2024_example_products": example_products,
        "msfs2024_source_refs": source_refs,
        "msfs2024_user_note": note,
        "msfs2024_last_verified_on": LAST_VERIFIED_ON,
    }


def available_manuals(products: list[str], note: str | None = None, *, included_tier: str = "included", channels: list[str] | None = None) -> dict[str, object]:
    return msfs_meta(
        "confirmed_available",
        True,
        note or "Confirmed as a current MSFS 2024 aircraft on the official aircraft manuals page.",
        products,
        [SOURCE_REFS["msfs2024_manuals"]],
        included_tier=included_tier,
        distribution_channels=channels or ["included_first_party"],
    )


def available_release(products: list[str], refs: list[str], note: str | None = None, *, included_tier: str = "included", channels: list[str] | None = None) -> dict[str, object]:
    return msfs_meta(
        "confirmed_available",
        True,
        note or "Confirmed as a current MSFS 2024 aircraft in official release notes.",
        products,
        refs,
        included_tier=included_tier,
        distribution_channels=channels or ["included_first_party"],
    )


def available_vendor(products: list[str], refs: list[str], note: str, *, included_tier: str = "", channels: list[str] | None = None) -> dict[str, object]:
    return msfs_meta(
        "confirmed_available",
        True,
        note,
        products,
        refs,
        included_tier=included_tier,
        distribution_channels=channels or ["third_party_paid"],
    )


def unavailable_vendor(products: list[str], refs: list[str], note: str, *, channels: list[str] | None = None) -> dict[str, object]:
    return msfs_meta(
        "confirmed_unavailable",
        False,
        note,
        products,
        refs,
        distribution_channels=channels or ["third_party_paid"],
    )


def not_verified(note: str = DEFAULT_NOT_VERIFIED_NOTE) -> dict[str, object]:
    return msfs_meta("not_verified", False, note, [], [])


def model(
    base: dict[str, object],
    meta: dict[str, object],
    model_id: str,
    family_id: str,
    display_name: str,
    short_name: str,
    variant_kind: str,
    in_service_role: str,
    max_passengers: int,
    max_cargo_lb: int,
    market_role_pool: str,
    best_fit_contract_tags: list[str],
    notes: str,
    **overrides: object,
) -> dict[str, object]:
    return base | meta | {
        "model_id": model_id,
        "family_id": family_id,
        "display_name": display_name,
        "short_name": short_name,
        "variant_kind": variant_kind,
        "in_service_role": in_service_role,
        "max_passengers": max_passengers,
        "max_cargo_lb": max_cargo_lb,
        "market_role_pool": market_role_pool,
        "best_fit_contract_tags": best_fit_contract_tags,
        "notes": notes,
    } | overrides


def cargo_capacity_for_layout(model: dict[str, object], total_seats: int, factor: float) -> int:
    max_cargo = int(model["max_cargo_lb"])
    if int(model["max_passengers"]) <= 0:
        return max_cargo
    seat_ratio = max(0.0, min(1.0, total_seats / int(model["max_passengers"])))
    modifier = 1.10 - (seat_ratio * 0.20)
    return min(max_cargo, int(round(max_cargo * modifier * factor)))


def make_layout(model: dict[str, object], suffix: str, display_name: str, config_type: str, *, total: int, first: int = 0, business: int = 0, premium: int = 0, economy: int = 0, cargo_factor: float = 1.0, is_default: bool = False, notes: str = "") -> dict[str, object]:
    return {
        "layout_id": f"{model['model_id']}__{suffix}",
        "model_id": model["model_id"],
        "display_name": display_name,
        "config_type": config_type,
        "is_default": is_default,
        "total_seats": total,
        "first_class_seats": first,
        "business_class_seats": business,
        "premium_economy_seats": premium,
        "economy_seats": economy,
        "cargo_capacity_lb": cargo_capacity_for_layout(model, total, cargo_factor),
        "notes": notes,
    }


FAMILIES = [
    family("caravan", "Cessna 208 Caravan family", "Textron Aviation / Cessna", "single_turboprop_utility", "single_turboprop_pt6", "caravan_single", ["utility_passenger", "utility_cargo", "remote_utility"], "Flexible early-game utility single for cargo and thin passenger work."),
    family("skycourier", "Cessna 408 SkyCourier family", "Textron Aviation / Cessna", "twin_turboprop_utility", "twin_turboprop_pt6", "skycourier", ["utility_cargo", "utility_passenger", "short_field"], "Utility twin focused on feeder cargo and small-community service."),
    family("pc12", "Pilatus PC-12 family", "Pilatus", "single_turboprop_premium", "single_turboprop_pt6", "pc12", ["premium_charter", "executive", "urgent"], "Premium single-turboprop lane for charter and high-value contracts."),
    family("citation_cj", "Citation CJ family", "Textron Aviation / Cessna", "light_business_jet", "light_business_jet", "citation_cj", ["premium_charter", "executive", "urgent"], "Fast premium-charter lane with low seat count and high urgency value."),
    family("citation_longitude", "Citation Longitude family", "Textron Aviation / Cessna", "super_midsize_business_jet", "super_midsize_business_jet", "citation_longitude", ["premium_charter", "executive", "long_range_charter"], "Long-range business jet lane above the CJ class."),
    family("pc24", "Pilatus PC-24 family", "Pilatus", "super_midsize_business_jet", "super_midsize_business_jet", "pc24", ["premium_charter", "short_field_jet", "urgent"], "Premium jet with unusually strong runway flexibility."),
    family("twin_otter", "DHC-6 Twin Otter family", "De Havilland Canada", "twin_turboprop_utility", "twin_turboprop_pt6", "twin_otter", ["rugged_remote_field", "remote_utility", "short_field"], "Remote-ops specialist with strong rough-field and short-field access."),
    family("skyvan", "Short SC.7 Skyvan family", "Short Brothers", "twin_turboprop_utility", "twin_turboprop_utility", "skyvan", ["rugged_remote_field", "remote_cargo", "rear_ramp"], "Boxy utility ramp aircraft for remote cargo and mixed work."),
    family("ys11", "NAMC YS-11 family", "NAMC", "regional_turboprop", "regional_turboprop", "ys11", ["regional_passenger", "thin_regional"], "Classic regional turboprop lane."),
    family("saab340", "Saab 340 family", "Saab", "twin_turboprop_commuter", "twin_turboprop_commuter", "saab340", ["commuter_passenger", "thin_regional", "feeder"], "Entry commuter twin for thin scheduled regional work."),
    family("beech1900", "Beechcraft 1900 family", "Beechcraft", "twin_turboprop_commuter", "twin_turboprop_commuter", "beech1900", ["commuter_passenger", "thin_regional"], "Small commuter twin for thin regional routes."),
    family("jetstream32", "Jetstream 32 family", "Jetstream / British Aerospace", "twin_turboprop_commuter", "twin_turboprop_commuter", "jetstream32", ["commuter_passenger", "thin_regional"], "Classic commuter turboprop candidate."),
    family("emb120", "Embraer EMB 120 family", "Embraer", "twin_turboprop_commuter", "twin_turboprop_commuter", "emb120", ["commuter_passenger", "thin_regional"], "Regional commuter turboprop between 1900 and Saab-class operations."),
    family("dash8", "Dash 8 family", "De Havilland Canada", "regional_turboprop", "regional_turboprop", "dash8", ["regional_passenger", "feeder"], "Modern regional turboprop workhorse."),
    family("atr", "ATR 42/72 family", "ATR / Hans Hartmann", "regional_turboprop", "regional_turboprop", "atr", ["regional_passenger", "regional_cargo", "combi"], "Core mid-game turboprop backbone for feeder passenger and freight lanes."),
    family("crj", "CRJ family", "Bombardier / Mitsubishi", "regional_jet", "regional_jet", "crj", ["regional_passenger", "speed"], "Regional jet line focused on speed and thin mainline feed."),
    family("erj145", "ERJ 145 family", "Embraer", "regional_jet", "regional_jet", "erj145", ["regional_passenger", "thin_regional"], "Small regional jet family for thin longer routes."),
    family("ejet", "Embraer E-Jet family", "Embraer", "regional_jet", "regional_jet", "ejet", ["regional_passenger", "mainline_bridge"], "Modern regional/mainline bridge jet family."),
    family("f28", "Fokker F28 family", "Fokker / Just Flight", "classic_regional_jet", "classic_regional_jet", "f28", ["regional_passenger", "classic_jet"], "Classic regional jet family for early jet expansion."),
    family("bae146", "BAe 146 family", "British Aerospace / Just Flight", "classic_regional_jet", "classic_regional_jet", "bae146", ["regional_passenger", "regional_cargo", "short_field_jet"], "Quiet regional jet family with passenger and freighter use cases."),
    family("avro_rj", "Avro RJ family", "British Aerospace / Just Flight", "classic_regional_jet", "classic_regional_jet", "avro_rj", ["regional_passenger", "regional_cargo", "short_field_jet"], "Updated RJ family above the 146 line."),
    family("a310", "Airbus A310 family", "Airbus", "widebody_airline", "widebody_airline", "a310", ["widebody_passenger", "medium_longhaul"], "Early widebody bridge for legacy long-haul operations."),
    family("a320_family", "Airbus A320 family", "Airbus / iniBuilds / FlyByWire", "narrowbody_airline", "narrowbody_airline", "airbus_narrowbody", ["narrowbody_passenger", "network_scale", "trunk_routes"], "Primary Airbus narrowbody lane for network growth and dense passenger work."),
    family("a220", "Airbus A220 family", "Airbus", "narrowbody_airline", "narrowbody_airline", "airbus_small_narrowbody", ["narrowbody_passenger", "thin_mainline"], "Small narrowbody family for thin mainline or premium regional flying."),
    family("b737", "Boeing 737 family", "Boeing / Asobo / PMDG", "narrowbody_airline", "narrowbody_airline", "boeing_737", ["narrowbody_passenger", "network_scale", "trunk_routes"], "Boeing narrowbody lane with mixed MSFS availability by variant."),
    family("a330", "Airbus A330 family", "Airbus / iniBuilds / Headwind Simulations", "widebody_airline", "widebody_airline", "airbus_widebody", ["widebody_passenger", "long_haul", "heavy_cargo"], "Widebody lane for long-haul and high-capacity network play."),
    family("a350", "Airbus A350 family", "Airbus / iniBuilds", "widebody_airline", "widebody_airline", "airbus_widebody_next", ["widebody_passenger", "flagship", "long_haul"], "Flagship late-game widebody lane."),
    family("b747", "Boeing 747 family", "Boeing", "widebody_airline", "widebody_airline", "boeing_747", ["widebody_passenger", "heavy_cargo", "flagship"], "Classic jumbo family for flagship and heavy cargo roles."),
    family("b787", "Boeing 787 family", "Boeing", "widebody_airline", "widebody_airline", "boeing_787", ["widebody_passenger", "long_haul", "modern_efficiency"], "Modern composite widebody family for long-haul growth."),
    family("b767", "Boeing 767 family", "Boeing", "widebody_airline", "widebody_airline", "boeing_767", ["widebody_passenger", "cargo_bridge"], "Versatile mid-sized widebody passenger and cargo family."),
    family("b777", "Boeing 777 family", "Boeing", "widebody_airline", "widebody_airline", "boeing_777", ["widebody_passenger", "long_haul", "heavy_cargo"], "Large twin-engine flagship family."),
    family("a300", "Airbus A300 family", "Airbus", "widebody_airline", "widebody_airline", "airbus_a300", ["heavy_cargo", "legacy_widebody"], "Legacy widebody freighter family."),
]

UTILITY_SINGLE = {"aircraft_category": "single_turboprop", "engine_type": "turboprop", "engine_count": 1, "fuel_type": "jet_a", "pressurized": False, "payload_class": "light", "combi_capable": False, "cruise_speed_ktas": 182, "range_nm": 900, "fuel_burn_gph": 72.0, "typical_turnaround_min": 30, "minimum_runway_ft": 2200, "preferred_runway_ft": 3000, "hard_surface_required": False, "rough_field_capable": True, "minimum_airport_size": 1, "preferred_airport_size": 2, "gate_requirement": "remote_stand_small", "required_ground_service_level": "light_ops", "cargo_loading_type": "bulk", "market_value_usd": 2200000, "target_lease_rate_monthly_usd": 38000, "variable_operating_cost_per_hour_usd": 550, "fixed_support_cost_per_day_usd": 220, "maintenance_reserve_per_hour_usd": 140, "pilot_qualification_group": "single_turboprop_utility", "pilots_required": 1, "flight_attendants_required": 0, "mechanic_skill_group": "single_turboprop_pt6", "base_dispatch_reliability": 0.965, "condition_decay_per_hour": 0.0050, "condition_decay_per_cycle": 0.0800, "inspection_interval_hours": 120, "inspection_interval_cycles": 90, "heavy_maintenance_band": "light_turboprop", "maintenance_downtime_hours": 36, "progression_tier": 1, "startup_eligible": True, "reputation_gate": 0, "airport_access_profile": "short_rough_friendly", "max_takeoff_weight_lb": 8750, "operating_empty_weight_lb": 5200, "max_payload_lb": 3300, "cargo_volume_cuft": 340, "max_usable_fuel_gal": 335, "wingspan_ft": 52, "aircraft_length_ft": 41, "tail_height_ft": 15, "icao_reference_code": "A", "approach_category": "A", "service_ceiling_ft": 25000, "takeoff_distance_ft": 2200, "landing_distance_ft": 1800, "layout_style": "utility", "data_confidence": "starter_design_band"}
UTILITY_TWIN = {"aircraft_category": "twin_turboprop", "engine_type": "turboprop", "engine_count": 2, "fuel_type": "jet_a", "pressurized": True, "payload_class": "medium", "combi_capable": False, "cruise_speed_ktas": 210, "range_nm": 900, "fuel_burn_gph": 165.0, "typical_turnaround_min": 35, "minimum_runway_ft": 2600, "preferred_runway_ft": 3600, "hard_surface_required": False, "rough_field_capable": True, "minimum_airport_size": 1, "preferred_airport_size": 2, "gate_requirement": "remote_stand_medium", "required_ground_service_level": "light_ops", "cargo_loading_type": "bulk", "market_value_usd": 4700000, "target_lease_rate_monthly_usd": 78000, "variable_operating_cost_per_hour_usd": 920, "fixed_support_cost_per_day_usd": 360, "maintenance_reserve_per_hour_usd": 280, "pilot_qualification_group": "twin_turboprop_utility", "pilots_required": 2, "flight_attendants_required": 0, "mechanic_skill_group": "twin_turboprop_pt6", "base_dispatch_reliability": 0.952, "condition_decay_per_hour": 0.0065, "condition_decay_per_cycle": 0.1100, "inspection_interval_hours": 110, "inspection_interval_cycles": 95, "heavy_maintenance_band": "utility_twin_turboprop", "maintenance_downtime_hours": 48, "progression_tier": 2, "startup_eligible": True, "reputation_gate": 6, "airport_access_profile": "remote_twin_capable", "max_takeoff_weight_lb": 19000, "operating_empty_weight_lb": 12000, "max_payload_lb": 6200, "cargo_volume_cuft": 900, "max_usable_fuel_gal": 520, "wingspan_ft": 72, "aircraft_length_ft": 55, "tail_height_ft": 20, "icao_reference_code": "B", "approach_category": "B", "service_ceiling_ft": 25000, "takeoff_distance_ft": 3200, "landing_distance_ft": 2400, "layout_style": "utility", "data_confidence": "starter_design_band"}
PREMIUM_SINGLE = {"aircraft_category": "single_turboprop", "engine_type": "turboprop", "engine_count": 1, "fuel_type": "jet_a", "pressurized": True, "payload_class": "light", "combi_capable": False, "cruise_speed_ktas": 285, "range_nm": 1600, "fuel_burn_gph": 82.0, "typical_turnaround_min": 25, "minimum_runway_ft": 2600, "preferred_runway_ft": 3400, "hard_surface_required": False, "rough_field_capable": False, "minimum_airport_size": 2, "preferred_airport_size": 2, "gate_requirement": "executive_apron", "required_ground_service_level": "executive_light", "cargo_loading_type": "bulk", "market_value_usd": 5400000, "target_lease_rate_monthly_usd": 90000, "variable_operating_cost_per_hour_usd": 780, "fixed_support_cost_per_day_usd": 320, "maintenance_reserve_per_hour_usd": 220, "pilot_qualification_group": "single_turboprop_premium", "pilots_required": 1, "flight_attendants_required": 0, "mechanic_skill_group": "single_turboprop_pt6", "base_dispatch_reliability": 0.972, "condition_decay_per_hour": 0.0044, "condition_decay_per_cycle": 0.0700, "inspection_interval_hours": 130, "inspection_interval_cycles": 100, "heavy_maintenance_band": "premium_single_turboprop", "maintenance_downtime_hours": 42, "progression_tier": 2, "startup_eligible": True, "reputation_gate": 10, "airport_access_profile": "premium_short_field", "max_takeoff_weight_lb": 10450, "operating_empty_weight_lb": 6600, "max_payload_lb": 3000, "cargo_volume_cuft": 400, "max_usable_fuel_gal": 402, "wingspan_ft": 53, "aircraft_length_ft": 47, "tail_height_ft": 14, "icao_reference_code": "A", "approach_category": "A", "service_ceiling_ft": 30000, "takeoff_distance_ft": 2600, "landing_distance_ft": 2100, "layout_style": "executive", "data_confidence": "starter_design_band"}
LIGHT_BIZJET = {"aircraft_category": "business_jet", "engine_type": "turbofan", "engine_count": 2, "fuel_type": "jet_a", "pressurized": True, "payload_class": "light", "combi_capable": False, "cruise_speed_ktas": 430, "range_nm": 1900, "fuel_burn_gph": 195.0, "typical_turnaround_min": 28, "minimum_runway_ft": 3400, "preferred_runway_ft": 4300, "hard_surface_required": True, "rough_field_capable": False, "minimum_airport_size": 2, "preferred_airport_size": 2, "gate_requirement": "executive_apron", "required_ground_service_level": "executive_jet", "cargo_loading_type": "bulk", "market_value_usd": 10400000, "target_lease_rate_monthly_usd": 180000, "variable_operating_cost_per_hour_usd": 1750, "fixed_support_cost_per_day_usd": 580, "maintenance_reserve_per_hour_usd": 430, "pilot_qualification_group": "light_business_jet", "pilots_required": 1, "flight_attendants_required": 0, "mechanic_skill_group": "light_business_jet", "base_dispatch_reliability": 0.968, "condition_decay_per_hour": 0.0052, "condition_decay_per_cycle": 0.0750, "inspection_interval_hours": 140, "inspection_interval_cycles": 120, "heavy_maintenance_band": "light_business_jet", "maintenance_downtime_hours": 52, "progression_tier": 4, "startup_eligible": False, "reputation_gate": 24, "airport_access_profile": "premium_paved", "max_takeoff_weight_lb": 17500, "operating_empty_weight_lb": 10800, "max_payload_lb": 5500, "cargo_volume_cuft": 520, "max_usable_fuel_gal": 970, "wingspan_ft": 53, "aircraft_length_ft": 53, "tail_height_ft": 16, "icao_reference_code": "A", "approach_category": "B", "service_ceiling_ft": 45000, "takeoff_distance_ft": 3600, "landing_distance_ft": 2800, "layout_style": "executive", "data_confidence": "starter_design_band"}
SUPER_MID_BIZJET = {"aircraft_category": "business_jet", "engine_type": "turbofan", "engine_count": 2, "fuel_type": "jet_a", "pressurized": True, "payload_class": "light", "combi_capable": False, "cruise_speed_ktas": 455, "range_nm": 2600, "fuel_burn_gph": 240.0, "typical_turnaround_min": 30, "minimum_runway_ft": 3500, "preferred_runway_ft": 4500, "hard_surface_required": True, "rough_field_capable": False, "minimum_airport_size": 2, "preferred_airport_size": 3, "gate_requirement": "executive_apron", "required_ground_service_level": "executive_jet_plus", "cargo_loading_type": "bulk", "market_value_usd": 13500000, "target_lease_rate_monthly_usd": 225000, "variable_operating_cost_per_hour_usd": 2150, "fixed_support_cost_per_day_usd": 720, "maintenance_reserve_per_hour_usd": 520, "pilot_qualification_group": "super_midsize_business_jet", "pilots_required": 2, "flight_attendants_required": 0, "mechanic_skill_group": "super_midsize_business_jet", "base_dispatch_reliability": 0.966, "condition_decay_per_hour": 0.0058, "condition_decay_per_cycle": 0.0800, "inspection_interval_hours": 145, "inspection_interval_cycles": 125, "heavy_maintenance_band": "super_midsize_business_jet", "maintenance_downtime_hours": 56, "progression_tier": 4, "startup_eligible": False, "reputation_gate": 28, "airport_access_profile": "premium_paved", "max_takeoff_weight_lb": 19500, "operating_empty_weight_lb": 12200, "max_payload_lb": 6500, "cargo_volume_cuft": 620, "max_usable_fuel_gal": 1300, "wingspan_ft": 56, "aircraft_length_ft": 56, "tail_height_ft": 18, "icao_reference_code": "A", "approach_category": "B", "service_ceiling_ft": 45000, "takeoff_distance_ft": 3800, "landing_distance_ft": 3000, "layout_style": "executive", "data_confidence": "starter_design_band"}
RUGGED_TWIN = {"aircraft_category": "twin_turboprop", "engine_type": "turboprop", "engine_count": 2, "fuel_type": "jet_a", "pressurized": False, "payload_class": "medium", "combi_capable": True, "cruise_speed_ktas": 175, "range_nm": 780, "fuel_burn_gph": 125.0, "typical_turnaround_min": 38, "minimum_runway_ft": 1500, "preferred_runway_ft": 2200, "hard_surface_required": False, "rough_field_capable": True, "minimum_airport_size": 1, "preferred_airport_size": 1, "gate_requirement": "remote_stand_medium", "required_ground_service_level": "remote_ops", "cargo_loading_type": "bulk", "market_value_usd": 4800000, "target_lease_rate_monthly_usd": 82000, "variable_operating_cost_per_hour_usd": 870, "fixed_support_cost_per_day_usd": 360, "maintenance_reserve_per_hour_usd": 290, "pilot_qualification_group": "twin_turboprop_utility", "pilots_required": 2, "flight_attendants_required": 0, "mechanic_skill_group": "twin_turboprop_pt6", "base_dispatch_reliability": 0.949, "condition_decay_per_hour": 0.0068, "condition_decay_per_cycle": 0.1150, "inspection_interval_hours": 105, "inspection_interval_cycles": 95, "heavy_maintenance_band": "remote_twin_turboprop", "maintenance_downtime_hours": 50, "progression_tier": 2, "startup_eligible": True, "reputation_gate": 8, "airport_access_profile": "remote_stol_specialist", "max_takeoff_weight_lb": 12500, "operating_empty_weight_lb": 7700, "max_payload_lb": 4500, "cargo_volume_cuft": 620, "max_usable_fuel_gal": 380, "wingspan_ft": 66, "aircraft_length_ft": 51, "tail_height_ft": 20, "icao_reference_code": "B", "approach_category": "A", "service_ceiling_ft": 25000, "takeoff_distance_ft": 1500, "landing_distance_ft": 1300, "layout_style": "utility", "data_confidence": "starter_design_band"}
COMMUTER_TURBOPROP = {"aircraft_category": "twin_turboprop", "engine_type": "turboprop", "engine_count": 2, "fuel_type": "jet_a", "pressurized": True, "payload_class": "medium", "combi_capable": False, "cruise_speed_ktas": 275, "range_nm": 900, "fuel_burn_gph": 205.0, "typical_turnaround_min": 40, "minimum_runway_ft": 3500, "preferred_runway_ft": 4500, "hard_surface_required": True, "rough_field_capable": False, "minimum_airport_size": 2, "preferred_airport_size": 3, "gate_requirement": "commuter_stand", "required_ground_service_level": "regional_light", "cargo_loading_type": "bulk", "market_value_usd": 6200000, "target_lease_rate_monthly_usd": 105000, "variable_operating_cost_per_hour_usd": 1200, "fixed_support_cost_per_day_usd": 480, "maintenance_reserve_per_hour_usd": 350, "pilot_qualification_group": "twin_turboprop_commuter", "pilots_required": 2, "flight_attendants_required": 1, "mechanic_skill_group": "twin_turboprop_commuter", "base_dispatch_reliability": 0.950, "condition_decay_per_hour": 0.0068, "condition_decay_per_cycle": 0.1200, "inspection_interval_hours": 105, "inspection_interval_cycles": 110, "heavy_maintenance_band": "commuter_turboprop", "maintenance_downtime_hours": 54, "progression_tier": 3, "startup_eligible": False, "reputation_gate": 18, "airport_access_profile": "regional_paved", "max_takeoff_weight_lb": 30000, "operating_empty_weight_lb": 18500, "max_payload_lb": 9000, "cargo_volume_cuft": 800, "max_usable_fuel_gal": 1250, "wingspan_ft": 70, "aircraft_length_ft": 65, "tail_height_ft": 20, "icao_reference_code": "B", "approach_category": "B", "service_ceiling_ft": 25000, "takeoff_distance_ft": 4200, "landing_distance_ft": 3400, "layout_style": "commuter", "data_confidence": "starter_design_band"}
REGIONAL_TURBOPROP = {"aircraft_category": "regional_turboprop", "engine_type": "turboprop", "engine_count": 2, "fuel_type": "jet_a", "pressurized": True, "payload_class": "regional", "combi_capable": True, "cruise_speed_ktas": 315, "range_nm": 900, "fuel_burn_gph": 285.0, "typical_turnaround_min": 48, "minimum_runway_ft": 4000, "preferred_runway_ft": 5200, "hard_surface_required": True, "rough_field_capable": False, "minimum_airport_size": 3, "preferred_airport_size": 3, "gate_requirement": "regional_gate", "required_ground_service_level": "regional_ops", "cargo_loading_type": "bulk", "market_value_usd": 13800000, "target_lease_rate_monthly_usd": 235000, "variable_operating_cost_per_hour_usd": 2000, "fixed_support_cost_per_day_usd": 760, "maintenance_reserve_per_hour_usd": 560, "pilot_qualification_group": "regional_turboprop", "pilots_required": 2, "flight_attendants_required": 1, "mechanic_skill_group": "regional_turboprop", "base_dispatch_reliability": 0.944, "condition_decay_per_hour": 0.0078, "condition_decay_per_cycle": 0.1400, "inspection_interval_hours": 100, "inspection_interval_cycles": 130, "heavy_maintenance_band": "regional_turboprop", "maintenance_downtime_hours": 60, "progression_tier": 4, "startup_eligible": False, "reputation_gate": 28, "airport_access_profile": "regional_paved", "max_takeoff_weight_lb": 50000, "operating_empty_weight_lb": 31000, "max_payload_lb": 18000, "cargo_volume_cuft": 1800, "max_usable_fuel_gal": 1650, "wingspan_ft": 90, "aircraft_length_ft": 90, "tail_height_ft": 25, "icao_reference_code": "C", "approach_category": "B", "service_ceiling_ft": 25000, "takeoff_distance_ft": 4300, "landing_distance_ft": 3600, "layout_style": "regional", "data_confidence": "starter_design_band"}
REGIONAL_JET = {"aircraft_category": "regional_jet", "engine_type": "turbofan", "engine_count": 2, "fuel_type": "jet_a", "pressurized": True, "payload_class": "regional", "combi_capable": False, "cruise_speed_ktas": 430, "range_nm": 1500, "fuel_burn_gph": 460.0, "typical_turnaround_min": 45, "minimum_runway_ft": 4800, "preferred_runway_ft": 6200, "hard_surface_required": True, "rough_field_capable": False, "minimum_airport_size": 3, "preferred_airport_size": 3, "gate_requirement": "regional_gate", "required_ground_service_level": "regional_ops", "cargo_loading_type": "bulk", "market_value_usd": 17000000, "target_lease_rate_monthly_usd": 280000, "variable_operating_cost_per_hour_usd": 2600, "fixed_support_cost_per_day_usd": 880, "maintenance_reserve_per_hour_usd": 720, "pilot_qualification_group": "regional_jet", "pilots_required": 2, "flight_attendants_required": 1, "mechanic_skill_group": "regional_jet", "base_dispatch_reliability": 0.944, "condition_decay_per_hour": 0.0082, "condition_decay_per_cycle": 0.1100, "inspection_interval_hours": 170, "inspection_interval_cycles": 155, "heavy_maintenance_band": "regional_jet", "maintenance_downtime_hours": 78, "progression_tier": 4, "startup_eligible": False, "reputation_gate": 32, "airport_access_profile": "regional_jet_paved", "max_takeoff_weight_lb": 80000, "operating_empty_weight_lb": 45000, "max_payload_lb": 20000, "cargo_volume_cuft": 1700, "max_usable_fuel_gal": 2900, "wingspan_ft": 82, "aircraft_length_ft": 105, "tail_height_ft": 27, "icao_reference_code": "C", "approach_category": "C", "service_ceiling_ft": 41000, "takeoff_distance_ft": 5600, "landing_distance_ft": 4600, "layout_style": "regional_jet", "data_confidence": "starter_design_band"}
CLASSIC_REGIONAL_JET = {"aircraft_category": "regional_jet", "engine_type": "turbofan", "engine_count": 2, "fuel_type": "jet_a", "pressurized": True, "payload_class": "regional", "combi_capable": False, "cruise_speed_ktas": 400, "range_nm": 1200, "fuel_burn_gph": 920.0, "typical_turnaround_min": 52, "minimum_runway_ft": 4500, "preferred_runway_ft": 6000, "hard_surface_required": True, "rough_field_capable": False, "minimum_airport_size": 3, "preferred_airport_size": 4, "gate_requirement": "regional_gate", "required_ground_service_level": "regional_ops", "cargo_loading_type": "bulk", "market_value_usd": 14000000, "target_lease_rate_monthly_usd": 230000, "variable_operating_cost_per_hour_usd": 3100, "fixed_support_cost_per_day_usd": 900, "maintenance_reserve_per_hour_usd": 850, "pilot_qualification_group": "classic_regional_jet", "pilots_required": 2, "flight_attendants_required": 1, "mechanic_skill_group": "classic_regional_jet", "base_dispatch_reliability": 0.939, "condition_decay_per_hour": 0.0089, "condition_decay_per_cycle": 0.1000, "inspection_interval_hours": 180, "inspection_interval_cycles": 160, "heavy_maintenance_band": "classic_regional_jet", "maintenance_downtime_hours": 96, "progression_tier": 5, "startup_eligible": False, "reputation_gate": 40, "airport_access_profile": "regional_jet_paved", "max_takeoff_weight_lb": 93000, "operating_empty_weight_lb": 53000, "max_payload_lb": 24000, "cargo_volume_cuft": 2500, "max_usable_fuel_gal": 5200, "wingspan_ft": 86, "aircraft_length_ft": 95, "tail_height_ft": 28, "icao_reference_code": "C", "approach_category": "C", "service_ceiling_ft": 35000, "takeoff_distance_ft": 5400, "landing_distance_ft": 4600, "layout_style": "regional_jet", "data_confidence": "starter_design_band"}
NARROWBODY_SMALL = {"aircraft_category": "narrowbody_airliner", "engine_type": "turbofan", "engine_count": 2, "fuel_type": "jet_a", "pressurized": True, "payload_class": "airliner", "combi_capable": False, "cruise_speed_ktas": 447, "range_nm": 3200, "fuel_burn_gph": 610.0, "typical_turnaround_min": 62, "minimum_runway_ft": 6200, "preferred_runway_ft": 7600, "hard_surface_required": True, "rough_field_capable": False, "minimum_airport_size": 3, "preferred_airport_size": 4, "gate_requirement": "narrowbody_gate", "required_ground_service_level": "narrowbody_ops", "cargo_loading_type": "containerized_light", "market_value_usd": 42000000, "target_lease_rate_monthly_usd": 620000, "variable_operating_cost_per_hour_usd": 5400, "fixed_support_cost_per_day_usd": 2200, "maintenance_reserve_per_hour_usd": 1800, "pilot_qualification_group": "narrowbody_airline", "pilots_required": 2, "flight_attendants_required": 3, "mechanic_skill_group": "narrowbody_airline", "base_dispatch_reliability": 0.944, "condition_decay_per_hour": 0.0080, "condition_decay_per_cycle": 0.0860, "inspection_interval_hours": 210, "inspection_interval_cycles": 180, "heavy_maintenance_band": "narrowbody_airliner", "maintenance_downtime_hours": 82, "progression_tier": 5, "startup_eligible": False, "reputation_gate": 48, "airport_access_profile": "mainline_paved", "max_takeoff_weight_lb": 149000, "operating_empty_weight_lb": 81000, "max_payload_lb": 32000, "cargo_volume_cuft": 3900, "max_usable_fuel_gal": 6500, "wingspan_ft": 115, "aircraft_length_ft": 127, "tail_height_ft": 38, "icao_reference_code": "C", "approach_category": "C", "service_ceiling_ft": 41000, "takeoff_distance_ft": 6100, "landing_distance_ft": 4800, "layout_style": "narrowbody", "data_confidence": "starter_design_band"}
NARROWBODY_STANDARD = {"aircraft_category": "narrowbody_airliner", "engine_type": "turbofan", "engine_count": 2, "fuel_type": "jet_a", "pressurized": True, "payload_class": "airliner", "combi_capable": False, "cruise_speed_ktas": 452, "range_nm": 3400, "fuel_burn_gph": 710.0, "typical_turnaround_min": 70, "minimum_runway_ft": 6500, "preferred_runway_ft": 8000, "hard_surface_required": True, "rough_field_capable": False, "minimum_airport_size": 4, "preferred_airport_size": 4, "gate_requirement": "narrowbody_gate", "required_ground_service_level": "narrowbody_ops", "cargo_loading_type": "containerized_light", "market_value_usd": 54000000, "target_lease_rate_monthly_usd": 790000, "variable_operating_cost_per_hour_usd": 6800, "fixed_support_cost_per_day_usd": 2750, "maintenance_reserve_per_hour_usd": 2200, "pilot_qualification_group": "narrowbody_airline", "pilots_required": 2, "flight_attendants_required": 4, "mechanic_skill_group": "narrowbody_airline", "base_dispatch_reliability": 0.942, "condition_decay_per_hour": 0.0085, "condition_decay_per_cycle": 0.0900, "inspection_interval_hours": 220, "inspection_interval_cycles": 180, "heavy_maintenance_band": "narrowbody_airliner", "maintenance_downtime_hours": 84, "progression_tier": 6, "startup_eligible": False, "reputation_gate": 52, "airport_access_profile": "mainline_paved", "max_takeoff_weight_lb": 181000, "operating_empty_weight_lb": 98000, "max_payload_lb": 46000, "cargo_volume_cuft": 5200, "max_usable_fuel_gal": 7200, "wingspan_ft": 118, "aircraft_length_ft": 130, "tail_height_ft": 41, "icao_reference_code": "C", "approach_category": "C", "service_ceiling_ft": 41000, "takeoff_distance_ft": 6500, "landing_distance_ft": 5200, "layout_style": "narrowbody", "data_confidence": "starter_design_band"}
NARROWBODY_STRETCH = {"aircraft_category": "narrowbody_airliner", "engine_type": "turbofan", "engine_count": 2, "fuel_type": "jet_a", "pressurized": True, "payload_class": "airliner", "combi_capable": False, "cruise_speed_ktas": 455, "range_nm": 3900, "fuel_burn_gph": 760.0, "typical_turnaround_min": 75, "minimum_runway_ft": 7000, "preferred_runway_ft": 8400, "hard_surface_required": True, "rough_field_capable": False, "minimum_airport_size": 4, "preferred_airport_size": 4, "gate_requirement": "narrowbody_gate", "required_ground_service_level": "narrowbody_ops", "cargo_loading_type": "containerized_light", "market_value_usd": 62000000, "target_lease_rate_monthly_usd": 890000, "variable_operating_cost_per_hour_usd": 7600, "fixed_support_cost_per_day_usd": 2950, "maintenance_reserve_per_hour_usd": 2450, "pilot_qualification_group": "narrowbody_airline", "pilots_required": 2, "flight_attendants_required": 4, "mechanic_skill_group": "narrowbody_airline", "base_dispatch_reliability": 0.940, "condition_decay_per_hour": 0.0087, "condition_decay_per_cycle": 0.0920, "inspection_interval_hours": 220, "inspection_interval_cycles": 180, "heavy_maintenance_band": "narrowbody_airliner", "maintenance_downtime_hours": 86, "progression_tier": 6, "startup_eligible": False, "reputation_gate": 56, "airport_access_profile": "mainline_paved", "max_takeoff_weight_lb": 216000, "operating_empty_weight_lb": 112000, "max_payload_lb": 54000, "cargo_volume_cuft": 6700, "max_usable_fuel_gal": 8700, "wingspan_ft": 118, "aircraft_length_ft": 146, "tail_height_ft": 41, "icao_reference_code": "C", "approach_category": "C", "service_ceiling_ft": 41000, "takeoff_distance_ft": 7200, "landing_distance_ft": 5600, "layout_style": "narrowbody", "data_confidence": "starter_design_band"}
WIDEBODY_MEDIUM = {"aircraft_category": "widebody_airliner", "engine_type": "turbofan", "engine_count": 2, "fuel_type": "jet_a", "pressurized": True, "payload_class": "heavy", "combi_capable": False, "cruise_speed_ktas": 470, "range_nm": 6200, "fuel_burn_gph": 1380.0, "typical_turnaround_min": 98, "minimum_runway_ft": 8200, "preferred_runway_ft": 9800, "hard_surface_required": True, "rough_field_capable": False, "minimum_airport_size": 4, "preferred_airport_size": 5, "gate_requirement": "widebody_gate", "required_ground_service_level": "widebody_ops", "cargo_loading_type": "containerized_heavy", "market_value_usd": 108000000, "target_lease_rate_monthly_usd": 1550000, "variable_operating_cost_per_hour_usd": 11800, "fixed_support_cost_per_day_usd": 4500, "maintenance_reserve_per_hour_usd": 3800, "pilot_qualification_group": "widebody_airline", "pilots_required": 2, "flight_attendants_required": 7, "mechanic_skill_group": "widebody_airline", "base_dispatch_reliability": 0.937, "condition_decay_per_hour": 0.0093, "condition_decay_per_cycle": 0.1080, "inspection_interval_hours": 250, "inspection_interval_cycles": 195, "heavy_maintenance_band": "widebody_airliner", "maintenance_downtime_hours": 116, "progression_tier": 7, "startup_eligible": False, "reputation_gate": 66, "airport_access_profile": "widebody_paved", "max_takeoff_weight_lb": 535000, "operating_empty_weight_lb": 275000, "max_payload_lb": 101000, "cargo_volume_cuft": 14500, "max_usable_fuel_gal": 25000, "wingspan_ft": 198, "aircraft_length_ft": 208, "tail_height_ft": 58, "icao_reference_code": "E", "approach_category": "D", "service_ceiling_ft": 41000, "takeoff_distance_ft": 9000, "landing_distance_ft": 6400, "layout_style": "widebody", "data_confidence": "starter_design_band"}
WIDEBODY_HEAVY = {"aircraft_category": "widebody_airliner", "engine_type": "turbofan", "engine_count": 2, "fuel_type": "jet_a", "pressurized": True, "payload_class": "heavy", "combi_capable": False, "cruise_speed_ktas": 482, "range_nm": 7800, "fuel_burn_gph": 1550.0, "typical_turnaround_min": 112, "minimum_runway_ft": 9000, "preferred_runway_ft": 10500, "hard_surface_required": True, "rough_field_capable": False, "minimum_airport_size": 5, "preferred_airport_size": 5, "gate_requirement": "widebody_gate_heavy", "required_ground_service_level": "widebody_heavy", "cargo_loading_type": "containerized_heavy", "market_value_usd": 160000000, "target_lease_rate_monthly_usd": 2300000, "variable_operating_cost_per_hour_usd": 15800, "fixed_support_cost_per_day_usd": 6400, "maintenance_reserve_per_hour_usd": 5200, "pilot_qualification_group": "widebody_airline", "pilots_required": 2, "flight_attendants_required": 9, "mechanic_skill_group": "widebody_airline", "base_dispatch_reliability": 0.934, "condition_decay_per_hour": 0.0098, "condition_decay_per_cycle": 0.1120, "inspection_interval_hours": 260, "inspection_interval_cycles": 200, "heavy_maintenance_band": "widebody_heavy", "maintenance_downtime_hours": 126, "progression_tier": 8, "startup_eligible": False, "reputation_gate": 78, "airport_access_profile": "widebody_heavy_paved", "max_takeoff_weight_lb": 775000, "operating_empty_weight_lb": 370000, "max_payload_lb": 160000, "cargo_volume_cuft": 20500, "max_usable_fuel_gal": 47000, "wingspan_ft": 213, "aircraft_length_ft": 242, "tail_height_ft": 61, "icao_reference_code": "E", "approach_category": "D", "service_ceiling_ft": 43000, "takeoff_distance_ft": 9800, "landing_distance_ft": 7200, "layout_style": "widebody", "data_confidence": "starter_design_band"}
HEAVY_FREIGHTER = {"aircraft_category": "widebody_freighter", "engine_type": "turbofan", "engine_count": 4, "fuel_type": "jet_a", "pressurized": True, "payload_class": "heavy", "combi_capable": False, "cruise_speed_ktas": 485, "range_nm": 4300, "fuel_burn_gph": 1780.0, "typical_turnaround_min": 120, "minimum_runway_ft": 9200, "preferred_runway_ft": 10800, "hard_surface_required": True, "rough_field_capable": False, "minimum_airport_size": 5, "preferred_airport_size": 5, "gate_requirement": "cargo_ramp_heavy", "required_ground_service_level": "heavy_cargo", "cargo_loading_type": "containerized_heavy", "market_value_usd": 145000000, "target_lease_rate_monthly_usd": 2150000, "variable_operating_cost_per_hour_usd": 17200, "fixed_support_cost_per_day_usd": 6500, "maintenance_reserve_per_hour_usd": 5400, "pilot_qualification_group": "widebody_airline", "pilots_required": 2, "flight_attendants_required": 0, "mechanic_skill_group": "widebody_airline", "base_dispatch_reliability": 0.932, "condition_decay_per_hour": 0.0102, "condition_decay_per_cycle": 0.1180, "inspection_interval_hours": 255, "inspection_interval_cycles": 185, "heavy_maintenance_band": "widebody_freighter", "maintenance_downtime_hours": 132, "progression_tier": 8, "startup_eligible": False, "reputation_gate": 80, "airport_access_profile": "heavy_cargo_hub_only", "max_takeoff_weight_lb": 987000, "operating_empty_weight_lb": 434000, "max_payload_lb": 300000, "cargo_volume_cuft": 30000, "max_usable_fuel_gal": 63000, "wingspan_ft": 224, "aircraft_length_ft": 250, "tail_height_ft": 64, "icao_reference_code": "F", "approach_category": "D", "service_ceiling_ft": 43000, "takeoff_distance_ft": 10200, "landing_distance_ft": 7600, "layout_style": "cargo", "data_confidence": "starter_design_band"}
WIDEBODY_LEGACY_FREIGHTER = {"aircraft_category": "widebody_freighter", "engine_type": "turbofan", "engine_count": 2, "fuel_type": "jet_a", "pressurized": True, "payload_class": "heavy", "combi_capable": False, "cruise_speed_ktas": 455, "range_nm": 4100, "fuel_burn_gph": 1320.0, "typical_turnaround_min": 105, "minimum_runway_ft": 8300, "preferred_runway_ft": 9800, "hard_surface_required": True, "rough_field_capable": False, "minimum_airport_size": 4, "preferred_airport_size": 5, "gate_requirement": "cargo_ramp_widebody", "required_ground_service_level": "heavy_cargo", "cargo_loading_type": "containerized_heavy", "market_value_usd": 82000000, "target_lease_rate_monthly_usd": 1180000, "variable_operating_cost_per_hour_usd": 9800, "fixed_support_cost_per_day_usd": 3800, "maintenance_reserve_per_hour_usd": 3200, "pilot_qualification_group": "widebody_airline", "pilots_required": 2, "flight_attendants_required": 0, "mechanic_skill_group": "widebody_airline", "base_dispatch_reliability": 0.931, "condition_decay_per_hour": 0.0097, "condition_decay_per_cycle": 0.1100, "inspection_interval_hours": 235, "inspection_interval_cycles": 180, "heavy_maintenance_band": "widebody_freighter", "maintenance_downtime_hours": 118, "progression_tier": 7, "startup_eligible": False, "reputation_gate": 70, "airport_access_profile": "widebody_cargo_paved", "max_takeoff_weight_lb": 375000, "operating_empty_weight_lb": 190000, "max_payload_lb": 120000, "cargo_volume_cuft": 16000, "max_usable_fuel_gal": 24000, "wingspan_ft": 148, "aircraft_length_ft": 177, "tail_height_ft": 55, "icao_reference_code": "D", "approach_category": "D", "service_ceiling_ft": 39000, "takeoff_distance_ft": 8800, "landing_distance_ft": 6200, "layout_style": "cargo", "data_confidence": "starter_design_band"}

MODELS = [
    model(UTILITY_SINGLE, available_release(["Cessna 208 B Grand Caravan EX"], [SOURCE_REFS["msfs2024_su1_forum"]]), "cessna_208b_grand_caravan_ex_passenger", "caravan", "Cessna 208 B Grand Caravan EX Passenger", "Caravan Passenger", "passenger", "Utility passenger turboprop", 10, 1600, "utility_passenger", ["regional_passenger", "thin_passenger", "remote_utility"], "Passenger-leaning Caravan variant for thin routes and small-community work."),
    model(UTILITY_SINGLE, available_release(["Cessna 208 B Grand Caravan EX"], [SOURCE_REFS["msfs2024_su1_forum"]]), "cessna_208b_grand_caravan_ex_cargo", "caravan", "Cessna 208 B Grand Caravan EX Cargo", "Caravan Cargo", "cargo", "Utility cargo turboprop", 0, 3300, "utility_cargo", ["light_cargo", "remote_cargo", "ad_hoc"], "Cargo-configured Caravan that keeps startup freight viable.", layout_style="cargo", cargo_loading_type="bulk"),
    model(UTILITY_TWIN, available_release(["Cessna 408 SkyCourier"], [SOURCE_REFS["msfs2024_su1_forum"], SOURCE_REFS["msfs2024_su4"]]), "cessna_408_skycourier_passenger", "skycourier", "Cessna 408 SkyCourier Passenger", "SkyCourier P", "passenger", "Utility passenger twin turboprop", 19, 2800, "utility_passenger", ["regional_passenger", "remote_utility", "thin_passenger"], "Utility passenger twin with stronger payload than a Caravan-class aircraft."),
    model(UTILITY_TWIN, available_release(["Cessna 408 SkyCourier"], [SOURCE_REFS["msfs2024_su1_forum"], SOURCE_REFS["msfs2024_su4"]]), "cessna_408_skycourier_freighter", "skycourier", "Cessna 408 SkyCourier Freighter", "SkyCourier F", "cargo", "Utility feeder freighter", 0, 6200, "utility_cargo", ["medium_cargo", "scheduled_cargo", "remote_cargo"], "Feeder cargo twin that expands payload without jumping to ATR-class costs.", layout_style="cargo", cargo_loading_type="bulk", market_value_usd=5200000, target_lease_rate_monthly_usd=86000, variable_operating_cost_per_hour_usd=980, maintenance_reserve_per_hour_usd=300),
    model(PREMIUM_SINGLE, available_release(["Pilatus PC-12 NGX"], [SOURCE_REFS["msfs2024_su4"]]), "pilatus_pc12_ngx", "pc12", "Pilatus PC-12 NGX", "PC-12 NGX", "executive", "Premium charter single turboprop", 8, 1800, "premium_charter", ["vip_charter", "urgent_charter", "premium_regional"], "High-margin single-engine charter aircraft for premium small-company play."),
    model(LIGHT_BIZJET, available_manuals(["Cessna Citation CJ4"], note="Confirmed in official MSFS 2024 documentation as a current first-party aircraft."), "cessna_citation_cj4", "citation_cj", "Cessna Citation CJ4", "Citation CJ4", "executive", "Light business jet", 8, 1000, "premium_charter", ["vip_charter", "urgent_charter", "executive"], "Speed-driven charter aircraft with low seat count and high schedule value."),
    model(SUPER_MID_BIZJET, available_manuals(["Cessna Citation Longitude"], note="Confirmed in official MSFS 2024 documentation as a current first-party aircraft."), "cessna_citation_longitude", "citation_longitude", "Cessna Citation Longitude", "Citation Longitude", "executive", "Super-midsize business jet", 12, 1500, "premium_charter", ["vip_charter", "urgent_charter", "executive_long_range"], "Long-range executive aircraft above the CJ lane.", max_takeoff_weight_lb=39200, operating_empty_weight_lb=23200, max_payload_lb=10900, cargo_volume_cuft=960, max_usable_fuel_gal=2900, wingspan_ft=69, aircraft_length_ft=73, tail_height_ft=26, icao_reference_code="B", approach_category="B", service_ceiling_ft=45000, takeoff_distance_ft=4800, landing_distance_ft=3500),
    model(SUPER_MID_BIZJET, available_release(["Pilatus PC-24"], [SOURCE_REFS["msfs2024_su4"], SOURCE_REFS["msfs2024_su4_early"]]), "pilatus_pc24", "pc24", "Pilatus PC-24", "PC-24", "executive", "Short-field capable business jet", 8, 2300, "premium_charter", ["vip_charter", "urgent_charter", "short_field_jet"], "Premium jet that reaches faster missions without fully surrendering runway flexibility.", minimum_runway_ft=2800, preferred_runway_ft=3800, rough_field_capable=True, market_value_usd=11700000, target_lease_rate_monthly_usd=200000, variable_operating_cost_per_hour_usd=1850, fixed_support_cost_per_day_usd=620, maintenance_reserve_per_hour_usd=460, max_takeoff_weight_lb=18300, operating_empty_weight_lb=11100, max_payload_lb=6500, cargo_volume_cuft=620, max_usable_fuel_gal=1260, wingspan_ft=56, aircraft_length_ft=56, tail_height_ft=17, takeoff_distance_ft=2950, landing_distance_ft=2550, gate_requirement="executive_apron", required_ground_service_level="executive_jet_plus"),
    model(RUGGED_TWIN, available_manuals(["DHC-6 Twin Otter"], note="Confirmed on the official MSFS aircraft manuals page as a current MSFS 2024 aircraft."), "dhc6_twin_otter_300", "twin_otter", "DHC-6 Twin Otter 300", "Twin Otter", "passenger_combi", "Rugged remote-field twin turboprop", 19, 4200, "rugged_remote_field", ["remote_passenger", "remote_cargo", "short_field"], "Remote access specialist for constrained strips and hard-to-serve airports.", combi_capable=True),
    model(UTILITY_TWIN, available_manuals(["Short SC.7 Skyvan 3-100"], note="Confirmed on the official MSFS aircraft manuals page as a current MSFS 2024 aircraft."), "short_sc7_skyvan_3_100", "skyvan", "Short SC.7 Skyvan 3-100", "Skyvan", "passenger_combi", "Ramp-equipped utility transport", 19, 6000, "rugged_remote_field", ["remote_cargo", "remote_passenger", "rear_ramp"], "Specialized utility ramp aircraft for remote strips and awkward cargo.", combi_capable=True, pressurized=False, cruise_speed_ktas=165, range_nm=650, fuel_burn_gph=155.0, typical_turnaround_min=42, minimum_runway_ft=1800, preferred_runway_ft=2600, hard_surface_required=False, rough_field_capable=True, minimum_airport_size=1, preferred_airport_size=1, gate_requirement="remote_ramp", required_ground_service_level="remote_ops", cargo_loading_type="rear_ramp", market_value_usd=3900000, target_lease_rate_monthly_usd=68000, variable_operating_cost_per_hour_usd=820, maintenance_reserve_per_hour_usd=260, max_takeoff_weight_lb=28500, operating_empty_weight_lb=15500, max_payload_lb=9000, cargo_volume_cuft=2400, max_usable_fuel_gal=620, wingspan_ft=64, aircraft_length_ft=40, tail_height_ft=19, icao_reference_code="B", approach_category="A", service_ceiling_ft=22000, takeoff_distance_ft=1900, landing_distance_ft=1700, layout_style="utility"),
    model(REGIONAL_TURBOPROP, available_manuals(["NAMC YS-11"], note="Confirmed on the official MSFS aircraft manuals page as a current MSFS 2024 aircraft."), "namc_ys11_100", "ys11", "NAMC YS-11-100", "YS-11", "passenger", "Classic regional turboprop", 60, 5000, "regional_passenger", ["regional_passenger", "thin_scheduled", "classic_airline"], "Classic regional turboprop that sits between commuter and full workhorse roles.", cruise_speed_ktas=255, range_nm=1200, fuel_burn_gph=360.0, minimum_runway_ft=4300, preferred_runway_ft=5200, market_value_usd=9000000, target_lease_rate_monthly_usd=150000, variable_operating_cost_per_hour_usd=1850, max_takeoff_weight_lb=53350, operating_empty_weight_lb=33000, max_payload_lb=14000, cargo_volume_cuft=1600, max_usable_fuel_gal=2400, wingspan_ft=108, aircraft_length_ft=87, tail_height_ft=28, icao_reference_code="C", approach_category="B", takeoff_distance_ft=5000, landing_distance_ft=4100),
    model(COMMUTER_TURBOPROP, available_release(["Saab 340B"], [SOURCE_REFS["msfs2024_su4"]]), "saab_340b", "saab340", "Saab 340B", "Saab 340B", "passenger", "Commuter turboprop airliner", 34, 2200, "commuter_passenger", ["regional_passenger", "feeder", "thin_scheduled"], "Classic commuter twin for early regional network building."),
    model(COMMUTER_TURBOPROP, not_verified(), "beechcraft_1900d", "beech1900", "Beechcraft 1900D", "Beech 1900D", "passenger", "Commuter turboprop airliner", 19, 2000, "commuter_passenger", ["thin_scheduled", "regional_passenger", "feeder"], "Useful small commuter candidate kept visible even without a confirmed MSFS overlap.", max_takeoff_weight_lb=17120, operating_empty_weight_lb=10500, max_payload_lb=4600, cargo_volume_cuft=420, max_usable_fuel_gal=660, wingspan_ft=57, aircraft_length_ft=57, tail_height_ft=15, icao_reference_code="A", approach_category="A", takeoff_distance_ft=3800, landing_distance_ft=3000, flight_attendants_required=0),
    model(COMMUTER_TURBOPROP, not_verified(), "jetstream_32", "jetstream32", "Jetstream 32", "Jetstream 32", "passenger", "Commuter turboprop airliner", 19, 1800, "commuter_passenger", ["thin_scheduled", "regional_passenger", "feeder"], "Useful commuter candidate kept visible even without a confirmed MSFS overlap.", cruise_speed_ktas=245, fuel_burn_gph=170.0, max_takeoff_weight_lb=16000, operating_empty_weight_lb=9600, max_payload_lb=4100, cargo_volume_cuft=380, max_usable_fuel_gal=620, wingspan_ft=52, aircraft_length_ft=48, tail_height_ft=16, icao_reference_code="A", approach_category="A", takeoff_distance_ft=3600, landing_distance_ft=2900, flight_attendants_required=0),
    model(COMMUTER_TURBOPROP, not_verified(), "embraer_emb120_brasilia", "emb120", "Embraer EMB 120 Brasilia", "EMB 120", "passenger", "Commuter turboprop airliner", 30, 2500, "commuter_passenger", ["regional_passenger", "feeder", "thin_scheduled"], "Useful 30-seat commuter step-up candidate for the world roster.", cruise_speed_ktas=300, range_nm=950, fuel_burn_gph=230.0, max_takeoff_weight_lb=26000, operating_empty_weight_lb=16000, max_payload_lb=7000, cargo_volume_cuft=550, max_usable_fuel_gal=1100, wingspan_ft=64, aircraft_length_ft=67, tail_height_ft=20, icao_reference_code="B", approach_category="B", takeoff_distance_ft=4300, landing_distance_ft=3500),
    model(REGIONAL_TURBOPROP, not_verified(), "dash8_q400", "dash8", "Dash 8 Q400", "Q400", "passenger", "High-speed regional turboprop", 78, 5000, "regional_passenger", ["regional_passenger", "dense_regional", "high_frequency"], "Fast regional turboprop workhorse that should exist in the broader FlightLine world even without a confirmed current MSFS path.", cruise_speed_ktas=360, range_nm=1100, fuel_burn_gph=390.0, minimum_runway_ft=4300, preferred_runway_ft=5400, market_value_usd=18000000, target_lease_rate_monthly_usd=310000, variable_operating_cost_per_hour_usd=2450, fixed_support_cost_per_day_usd=900, maintenance_reserve_per_hour_usd=650, max_takeoff_weight_lb=64500, operating_empty_weight_lb=39000, max_payload_lb=19000, cargo_volume_cuft=1900, max_usable_fuel_gal=1750, wingspan_ft=94, aircraft_length_ft=107, tail_height_ft=27, icao_reference_code="C", approach_category="B", takeoff_distance_ft=4600, landing_distance_ft=3900),
    model(REGIONAL_TURBOPROP, available_vendor(["Expert Series 01: ATR 42-600 / 72-600"], [SOURCE_REFS["msfs_atr"], SOURCE_REFS["msfs_atr_bundle"]], "Available to MSFS users through the official ATR package and current Content Manager support.", included_tier="owned_addon", channels=["official_content_manager_addon"]), "atr_42_600_combi", "atr", "ATR 42-600 Combi", "ATR 42 Combi", "combi", "Regional turboprop combi", 42, 8000, "regional_passenger", ["regional_passenger", "combi", "feeder"], "Balanced feeder aircraft that keeps both passenger and freight options open.", market_value_usd=12800000, target_lease_rate_monthly_usd=220000, variable_operating_cost_per_hour_usd=1900, maintenance_reserve_per_hour_usd=520, max_takeoff_weight_lb=41000, operating_empty_weight_lb=27000, max_payload_lb=14000, cargo_volume_cuft=1400, max_usable_fuel_gal=1500, wingspan_ft=81, aircraft_length_ft=74, tail_height_ft=24, icao_reference_code="C", approach_category="B", takeoff_distance_ft=4300, landing_distance_ft=3500),
    model(REGIONAL_TURBOPROP, available_vendor(["Expert Series 01: ATR 42-600 / 72-600"], [SOURCE_REFS["msfs_atr"], SOURCE_REFS["msfs_atr_bundle"]], "Available to MSFS users through the official ATR package and current Content Manager support.", included_tier="owned_addon", channels=["official_content_manager_addon"]), "atr_72_600_passenger", "atr", "ATR 72-600 Passenger", "ATR 72-600", "passenger", "Regional turboprop airliner", 72, 4500, "regional_passenger", ["regional_passenger", "dense_regional", "scheduled_passenger"], "Passenger-focused ATR workhorse for denser feeder networks.", max_takeoff_weight_lb=50000, operating_empty_weight_lb=31000, max_payload_lb=17500, cargo_volume_cuft=1800, max_usable_fuel_gal=1650, wingspan_ft=89, aircraft_length_ft=90, tail_height_ft=25, icao_reference_code="C", approach_category="B", takeoff_distance_ft=4500, landing_distance_ft=3700),
    model(REGIONAL_TURBOPROP, available_vendor(["Expert Series 01: ATR 42-600 / 72-600", "ATR 72-600F"], [SOURCE_REFS["msfs_atr"], SOURCE_REFS["msfs_atr_bundle"]], "Available to MSFS users through the official ATR package, including the 72-600F freighter update.", included_tier="owned_addon", channels=["official_content_manager_addon"]), "atr_72_600f", "atr", "ATR 72-600F", "ATR 72F", "cargo", "Regional feeder freighter", 0, 17000, "regional_cargo_combi", ["scheduled_cargo", "feeder_cargo", "dense_regional"], "Dedicated regional freight aircraft for denser cargo boards.", layout_style="cargo", combi_capable=False, cargo_loading_type="palletized", max_takeoff_weight_lb=50000, operating_empty_weight_lb=31500, max_payload_lb=18000, cargo_volume_cuft=2200, max_usable_fuel_gal=1650, wingspan_ft=89, aircraft_length_ft=90, tail_height_ft=25, icao_reference_code="C", approach_category="B", takeoff_distance_ft=4600, landing_distance_ft=3800, flight_attendants_required=0),
    model(REGIONAL_JET, not_verified(), "crj700", "crj", "CRJ700", "CRJ700", "passenger", "Regional jet airliner", 70, 3500, "regional_passenger", ["regional_passenger", "thin_mainline", "speed"], "Regional jet candidate that belongs in the broader world roster even without a confirmed current MSFS path.", max_takeoff_weight_lb=76000, operating_empty_weight_lb=43000, max_payload_lb=19000, cargo_volume_cuft=1800, max_usable_fuel_gal=2900, wingspan_ft=76, aircraft_length_ft=106, tail_height_ft=27, icao_reference_code="C", approach_category="C", takeoff_distance_ft=5800, landing_distance_ft=4800),
    model(REGIONAL_JET, not_verified(), "embraer_erj145xr", "erj145", "Embraer ERJ 145XR", "ERJ 145XR", "passenger", "Small regional jet airliner", 50, 2500, "regional_passenger", ["regional_passenger", "thin_mainline", "speed"], "Useful small regional jet for thinner long sectors.", cruise_speed_ktas=430, range_nm=1750, fuel_burn_gph=340.0, max_takeoff_weight_lb=48500, operating_empty_weight_lb=27000, max_payload_lb=11000, cargo_volume_cuft=1000, max_usable_fuel_gal=2050, wingspan_ft=66, aircraft_length_ft=98, tail_height_ft=22, icao_reference_code="B", approach_category="B", takeoff_distance_ft=5600, landing_distance_ft=4500),
    model(REGIONAL_JET, not_verified(), "embraer_e175", "ejet", "Embraer E175", "E175", "passenger", "Regional jet airliner", 76, 3500, "regional_passenger", ["regional_passenger", "thin_mainline", "speed"], "Modern E-Jet bridge between regional and mainline operations.", cruise_speed_ktas=447, range_nm=1900, fuel_burn_gph=470.0, market_value_usd=26000000, target_lease_rate_monthly_usd=390000, variable_operating_cost_per_hour_usd=3200, maintenance_reserve_per_hour_usd=820, max_takeoff_weight_lb=89000, operating_empty_weight_lb=51000, max_payload_lb=22000, cargo_volume_cuft=2600, max_usable_fuel_gal=3450, wingspan_ft=86, aircraft_length_ft=104, tail_height_ft=34, icao_reference_code="C", approach_category="C", takeoff_distance_ft=6100, landing_distance_ft=5000),
    model(REGIONAL_JET, not_verified(), "embraer_e190", "ejet", "Embraer E190", "E190", "passenger", "Regional/mainline bridge jet", 100, 5000, "regional_passenger", ["regional_passenger", "mainline_bridge", "speed"], "Larger E-Jet bridge model for higher-demand regional and short mainline sectors.", cruise_speed_ktas=454, range_nm=2400, fuel_burn_gph=590.0, market_value_usd=32000000, target_lease_rate_monthly_usd=470000, variable_operating_cost_per_hour_usd=4100, maintenance_reserve_per_hour_usd=1100, max_takeoff_weight_lb=113000, operating_empty_weight_lb=62000, max_payload_lb=28000, cargo_volume_cuft=3200, max_usable_fuel_gal=4300, wingspan_ft=94, aircraft_length_ft=119, tail_height_ft=35, icao_reference_code="C", approach_category="C", takeoff_distance_ft=6500, landing_distance_ft=5300),
    model(CLASSIC_REGIONAL_JET, available_vendor(["F28 Professional"], [SOURCE_REFS["justflight_f28"]], "Confirmed on the official Just Flight product page as an MSFS product.", channels=["third_party_paid", "marketplace_paid"]), "fokker_f28_mk4000", "f28", "Fokker F28 Mk4000", "F28-4000", "passenger", "Classic regional jet airliner", 65, 3500, "regional_passenger", ["regional_passenger", "classic_jet", "speed"], "Classic regional jet family that sits between turboprops and larger mainline narrowbodies.", cruise_speed_ktas=430, range_nm=1500, fuel_burn_gph=980.0, market_value_usd=17000000, target_lease_rate_monthly_usd=270000, max_takeoff_weight_lb=73000, operating_empty_weight_lb=39000, max_payload_lb=18000, cargo_volume_cuft=2000, max_usable_fuel_gal=4300, wingspan_ft=76, aircraft_length_ft=97, tail_height_ft=28, icao_reference_code="C", approach_category="C", takeoff_distance_ft=6200, landing_distance_ft=4700),
    model(CLASSIC_REGIONAL_JET, available_vendor(["Just Flight 146 Professional"], [SOURCE_REFS["justflight_146"]], "Confirmed on the official Just Flight product page as compatible with MSFS 2024 and 2020.", channels=["third_party_paid", "marketplace_paid"]), "bae_146_300", "bae146", "BAe 146-300", "146-300", "passenger", "Quiet regional jet airliner", 112, 4500, "regional_passenger", ["regional_passenger", "short_field_jet", "city_airport"], "Passenger 146 variant for dense regional or city-airport focused operations.", max_takeoff_weight_lb=93000, operating_empty_weight_lb=53000, max_payload_lb=24000, cargo_volume_cuft=2500, max_usable_fuel_gal=5200, wingspan_ft=86, aircraft_length_ft=109, tail_height_ft=28, icao_reference_code="C", approach_category="C", takeoff_distance_ft=5400, landing_distance_ft=4500),
    model(CLASSIC_REGIONAL_JET, available_vendor(["Just Flight 146 Professional"], [SOURCE_REFS["justflight_146"]], "Confirmed on the official Just Flight product page as compatible with MSFS 2024 and 2020.", channels=["third_party_paid", "marketplace_paid"]), "bae_146_200_qt", "bae146", "BAe 146-200 QT", "146-200 QT", "cargo", "Quiet regional freighter", 0, 26000, "regional_cargo_combi", ["night_cargo", "regional_cargo", "short_field_jet"], "Distinct late-midgame regional freighter with strong city-airport identity.", layout_style="cargo", combi_capable=False, cargo_loading_type="palletized", flight_attendants_required=0, max_takeoff_weight_lb=93000, operating_empty_weight_lb=52000, max_payload_lb=26000, cargo_volume_cuft=3400, max_usable_fuel_gal=5200, wingspan_ft=86, aircraft_length_ft=94, tail_height_ft=28, icao_reference_code="C", approach_category="C", takeoff_distance_ft=5300, landing_distance_ft=4400),
    model(CLASSIC_REGIONAL_JET, available_vendor(["RJ Professional"], [SOURCE_REFS["justflight_rj"]], "Confirmed on the official Just Flight product page as compatible with MSFS 2024 and 2020.", channels=["third_party_paid", "marketplace_paid"]), "avro_rj85", "avro_rj", "Avro RJ85", "RJ85", "passenger", "Regional jet airliner", 95, 4200, "regional_passenger", ["regional_passenger", "short_field_jet", "city_airport"], "Modernized RJ-family passenger variant above the 146.", cruise_speed_ktas=432, range_nm=1600, fuel_burn_gph=950.0, market_value_usd=19000000, target_lease_rate_monthly_usd=300000, max_takeoff_weight_lb=97000, operating_empty_weight_lb=56000, max_payload_lb=25000, cargo_volume_cuft=2600, max_usable_fuel_gal=5400, wingspan_ft=86, aircraft_length_ft=104, tail_height_ft=28, icao_reference_code="C", approach_category="C", takeoff_distance_ft=5600, landing_distance_ft=4500),
    model(CLASSIC_REGIONAL_JET, available_vendor(["RJ Professional"], [SOURCE_REFS["justflight_rj"]], "Confirmed on the official Just Flight product page as compatible with MSFS 2024 and 2020.", channels=["third_party_paid", "marketplace_paid"]), "avro_rj100_qt", "avro_rj", "Avro RJ100 QT", "RJ100 QT", "cargo", "Regional jet freighter", 0, 29000, "regional_cargo_combi", ["night_cargo", "regional_cargo", "short_field_jet"], "Quiet regional freighter derived from the RJ family.", layout_style="cargo", combi_capable=False, cargo_loading_type="palletized", flight_attendants_required=0, cruise_speed_ktas=430, range_nm=1450, fuel_burn_gph=960.0, market_value_usd=18500000, target_lease_rate_monthly_usd=295000, max_takeoff_weight_lb=98000, operating_empty_weight_lb=55500, max_payload_lb=29000, cargo_volume_cuft=3600, max_usable_fuel_gal=5400, wingspan_ft=86, aircraft_length_ft=115, tail_height_ft=28, icao_reference_code="C", approach_category="C", takeoff_distance_ft=5700, landing_distance_ft=4550),
    model(WIDEBODY_MEDIUM, available_manuals(["Airbus A310-300"], note="Confirmed on the official MSFS aircraft manuals page as a current MSFS 2024 aircraft."), "airbus_a310_300", "a310", "Airbus A310-300", "A310-300", "passenger", "Legacy widebody passenger airliner", 280, 52000, "aspirational_stretch", ["longhaul_passenger", "widebody_bridge", "hub_spoke"], "Legacy widebody bridge aircraft for medium-to-long-haul passenger service.", cruise_speed_ktas=470, range_nm=5100, fuel_burn_gph=1340.0, market_value_usd=78000000, target_lease_rate_monthly_usd=1100000, max_takeoff_weight_lb=363000, operating_empty_weight_lb=176000, max_payload_lb=87000, cargo_volume_cuft=10500, max_usable_fuel_gal=25000, wingspan_ft=144, aircraft_length_ft=151, tail_height_ft=52, icao_reference_code="D", approach_category="D", takeoff_distance_ft=8700, landing_distance_ft=6100),
    model(NARROWBODY_STANDARD, available_manuals(["Airbus A320neo V2"], note="Built into MSFS 2024 and also represented on PC by the officially compatible FlyByWire A32NX.", channels=["included_first_party", "third_party_freeware"]), "airbus_a320neo", "a320_family", "Airbus A320neo", "A320neo", "passenger", "Narrowbody passenger airliner", 180, 43000, "aspirational_stretch", ["trunk_passenger", "dense_regional", "scheduled_passenger"], "Core Airbus narrowbody entry for dense scheduled passenger expansion.", msfs2024_distribution_channels=["included_first_party", "third_party_freeware"], msfs2024_source_refs=[SOURCE_REFS["msfs2024_manuals"], SOURCE_REFS["flybywire_a32nx"]]),
    model(NARROWBODY_STRETCH, available_manuals(["Airbus A321LR"], note="Confirmed on the official MSFS aircraft manuals page as a current MSFS 2024 aircraft."), "airbus_a321lr", "a320_family", "Airbus A321LR", "A321LR", "passenger", "Long-range narrowbody airliner", 206, 49000, "aspirational_stretch", ["trunk_passenger", "long_thin", "scheduled_passenger"], "Longer-range Airbus narrowbody variant for higher-capacity and thinner transcontinental routes."),
    model(NARROWBODY_SMALL, not_verified(), "airbus_a220_300", "a220", "Airbus A220-300", "A220-300", "passenger", "Small narrowbody airliner", 145, 32000, "aspirational_stretch", ["thin_mainline", "premium_regional", "scheduled_passenger"], "Small narrowbody that belongs in the FlightLine world even without a confirmed current MSFS overlap.", cruise_speed_ktas=455, range_nm=3300, fuel_burn_gph=590.0, market_value_usd=46000000, target_lease_rate_monthly_usd=670000, max_takeoff_weight_lb=149000, operating_empty_weight_lb=81000, max_payload_lb=32000, cargo_volume_cuft=3900, max_usable_fuel_gal=6500, wingspan_ft=115, aircraft_length_ft=127, tail_height_ft=38, icao_reference_code="C", approach_category="C", takeoff_distance_ft=6100, landing_distance_ft=4800),
    model(NARROWBODY_STANDARD, available_release(["Boeing 737 MAX 8"], [SOURCE_REFS["msfs2024_su4_early"]]), "boeing_737_max_8", "b737", "Boeing 737 MAX 8", "737 MAX 8", "passenger", "Narrowbody passenger airliner", 189, 46000, "aspirational_stretch", ["trunk_passenger", "scheduled_passenger", "network_scale"], "Core Boeing narrowbody option for dense passenger growth."),
    model(NARROWBODY_STANDARD, not_verified(), "boeing_737_800", "b737", "Boeing 737-800", "737-800", "passenger", "Narrowbody passenger airliner", 189, 45000, "aspirational_stretch", ["trunk_passenger", "scheduled_passenger", "network_scale"], "Very common real-world narrowbody that should exist in the in-game catalog regardless of MSFS overlap.", market_value_usd=50000000, target_lease_rate_monthly_usd=720000, max_takeoff_weight_lb=174000, operating_empty_weight_lb=91500, max_payload_lb=45000, cargo_volume_cuft=5000, max_usable_fuel_gal=6900, wingspan_ft=117, aircraft_length_ft=130, tail_height_ft=41, icao_reference_code="C", approach_category="C", takeoff_distance_ft=6500, landing_distance_ft=5200),
    model(NARROWBODY_STRETCH, unavailable_vendor(["PMDG 737-900", "PMDG 737-900ER"], [SOURCE_REFS["pmdg_737_900"]], "The current PMDG product page warns that this 737-900 package is not compatible with MSFS 2024."), "boeing_737_900er", "b737", "Boeing 737-900ER", "737-900ER", "passenger", "Narrowbody stretch airliner", 215, 47000, "aspirational_stretch", ["trunk_passenger", "scheduled_passenger", "network_scale"], "Stored as a real roster candidate, but currently marked unavailable to the user in MSFS 2024.", market_value_usd=52000000, target_lease_rate_monthly_usd=770000, variable_operating_cost_per_hour_usd=7000, fixed_support_cost_per_day_usd=2820, maintenance_reserve_per_hour_usd=2320, range_nm=3200),
    model(WIDEBODY_MEDIUM, available_manuals(["Airbus A330-300"], note="Confirmed on the official MSFS aircraft manuals page as a current first-party aircraft."), "airbus_a330_300", "a330", "Airbus A330-300", "A330-300", "passenger", "Widebody passenger airliner", 290, 70000, "aspirational_stretch", ["longhaul_passenger", "heavy_passenger", "hub_spoke"], "First-party A330 anchor for widebody progression.", range_nm=6100, fuel_burn_gph=1480.0, market_value_usd=105000000, target_lease_rate_monthly_usd=1500000),
    model(WIDEBODY_MEDIUM, available_vendor(["Headwind Simulations A339X"], [SOURCE_REFS["headwind_home"]], "Confirmed as a freeware add-on for Microsoft Flight Simulator on the official Headwind Simulations site.", channels=["third_party_freeware"]), "airbus_a330_900neo", "a330", "Airbus A330-900neo", "A330-900neo", "passenger", "Widebody passenger airliner", 300, 72000, "aspirational_stretch", ["longhaul_passenger", "heavy_passenger", "hub_spoke"], "Freeware long-haul A330neo path for users who want a current PC add-on overlap.", range_nm=6500, market_value_usd=118000000, target_lease_rate_monthly_usd=1650000),
    model(WIDEBODY_HEAVY, available_vendor(["iniBuilds A350 Airliner"], [SOURCE_REFS["inibuilds_a350"]], "Confirmed on the official iniBuilds store as an MSFS 2024 product."), "airbus_a350_900", "a350", "Airbus A350-900", "A350-900", "passenger", "Flagship widebody airliner", 325, 80000, "aspirational_stretch", ["flagship_passenger", "longhaul_passenger", "premium_longhaul"], "Late-game flagship passenger aircraft with the heaviest prestige and capital burden in the starter set.", cruise_speed_ktas=488, range_nm=8200, fuel_burn_gph=1520.0, minimum_runway_ft=9000, preferred_runway_ft=10500, market_value_usd=165000000, target_lease_rate_monthly_usd=2400000, progression_tier=8, reputation_gate=80, max_takeoff_weight_lb=623000, operating_empty_weight_lb=308000, max_payload_lb=120000, cargo_volume_cuft=15500, max_usable_fuel_gal=43000, wingspan_ft=213, aircraft_length_ft=219, tail_height_ft=57, icao_reference_code="E", approach_category="D", takeoff_distance_ft=9400, landing_distance_ft=6900),
    model(WIDEBODY_HEAVY, available_manuals(["Boeing 747-8 Intercontinental"], note="Confirmed on the official MSFS aircraft manuals page as a current MSFS 2024 aircraft."), "boeing_747_8i", "b747", "Boeing 747-8 Intercontinental", "747-8I", "passenger", "Jumbo widebody passenger airliner", 410, 90000, "aspirational_stretch", ["flagship_passenger", "hub_spoke", "longhaul_passenger"], "Large flagship passenger aircraft for high-density long-haul trunk routes.", cruise_speed_ktas=490, range_nm=7600, fuel_burn_gph=1950.0, market_value_usd=175000000, target_lease_rate_monthly_usd=2450000, max_takeoff_weight_lb=987000, operating_empty_weight_lb=485000, max_payload_lb=172000, cargo_volume_cuft=21000, max_usable_fuel_gal=63100, wingspan_ft=224, aircraft_length_ft=251, tail_height_ft=64, icao_reference_code="F", approach_category="D", takeoff_distance_ft=10300, landing_distance_ft=7600, minimum_airport_size=5, preferred_airport_size=5, gate_requirement="widebody_gate_heavy", required_ground_service_level="widebody_heavy"),
    model(HEAVY_FREIGHTER, available_manuals(["Boeing 747-8F"], note="Confirmed on the official MSFS aircraft manuals page as a current MSFS 2024 aircraft."), "boeing_747_8f", "b747", "Boeing 747-8F", "747-8F", "cargo", "Heavy widebody freighter", 0, 300000, "mainline_cargo", ["heavy_cargo", "hub_freight", "flagship_cargo"], "Top-end freighter for hub cargo operations.", layout_style="cargo", cargo_loading_type="nose_door_containerized", flight_attendants_required=0),
    model(WIDEBODY_MEDIUM, available_manuals(["Boeing 787-10"], note="Confirmed on the official MSFS aircraft manuals page as a current MSFS 2024 aircraft."), "boeing_787_10", "b787", "Boeing 787-10", "787-10", "passenger", "Modern widebody passenger airliner", 318, 76000, "aspirational_stretch", ["longhaul_passenger", "modern_efficiency", "hub_spoke"], "Modern long-haul twin built for efficient dense long sectors.", cruise_speed_ktas=486, range_nm=6400, fuel_burn_gph=1420.0, market_value_usd=150000000, target_lease_rate_monthly_usd=2050000, max_takeoff_weight_lb=560000, operating_empty_weight_lb=285000, max_payload_lb=110000, cargo_volume_cuft=15000, max_usable_fuel_gal=33300, wingspan_ft=197, aircraft_length_ft=224, tail_height_ft=56, icao_reference_code="E", approach_category="D", takeoff_distance_ft=9300, landing_distance_ft=6600),
    model(WIDEBODY_MEDIUM, not_verified(), "boeing_767_300er", "b767", "Boeing 767-300ER", "767-300ER", "passenger", "Widebody passenger airliner", 260, 65000, "aspirational_stretch", ["longhaul_passenger", "widebody_bridge", "hub_spoke"], "Very common real-world widebody that should exist in FlightLine whether or not the player also flies it in MSFS.", cruise_speed_ktas=470, range_nm=5900, fuel_burn_gph=1360.0, market_value_usd=88000000, target_lease_rate_monthly_usd=1250000, max_takeoff_weight_lb=412000, operating_empty_weight_lb=200000, max_payload_lb=120000, cargo_volume_cuft=15000, max_usable_fuel_gal=24000, wingspan_ft=156, aircraft_length_ft=180, tail_height_ft=52, icao_reference_code="D", approach_category="D", takeoff_distance_ft=8900, landing_distance_ft=6200),
    model(WIDEBODY_HEAVY, not_verified(), "boeing_777_300er", "b777", "Boeing 777-300ER", "777-300ER", "passenger", "Large twin widebody airliner", 365, 88000, "aspirational_stretch", ["longhaul_passenger", "flagship_passenger", "hub_spoke"], "Global flagship long-haul twin that belongs in the world roster.", cruise_speed_ktas=489, range_nm=7300, fuel_burn_gph=1680.0, market_value_usd=170000000, target_lease_rate_monthly_usd=2350000, max_takeoff_weight_lb=775000, operating_empty_weight_lb=370000, max_payload_lb=160000, cargo_volume_cuft=20000, max_usable_fuel_gal=47000, wingspan_ft=213, aircraft_length_ft=242, tail_height_ft=61, icao_reference_code="E", approach_category="D", takeoff_distance_ft=9800, landing_distance_ft=7200),
    model(WIDEBODY_LEGACY_FREIGHTER, not_verified(), "airbus_a300_600f", "a300", "Airbus A300-600F", "A300-600F", "cargo", "Legacy widebody freighter", 0, 120000, "mainline_cargo", ["heavy_cargo", "hub_freight", "medium_longhaul_cargo"], "Legacy cargo specialist that should be acquirable even without MSFS overlap.", layout_style="cargo", cargo_loading_type="containerized_heavy", flight_attendants_required=0),
]


def build_cabin_layouts(models: list[dict[str, object]]) -> list[dict[str, object]]:
    layouts: list[dict[str, object]] = []
    for model_item in models:
        max_pax = int(model_item["max_passengers"])
        style = str(model_item.get("layout_style", ""))
        if max_pax <= 0 or style == "cargo":
            continue
        if style == "executive":
            layouts.append(make_layout(model_item, "executive", "Executive Layout", "executive", total=max_pax, business=max_pax, cargo_factor=0.95, is_default=True, notes="Single-cabin premium executive layout."))
            continue
        if style == "utility":
            layouts.append(make_layout(model_item, "utility_standard", "Utility Standard", "single_class", total=max_pax, economy=max_pax, cargo_factor=0.88, is_default=True, notes="Simple all-economy or bench-seating utility layout."))
            combi_total = max(6, int(round(max_pax * 0.7)))
            layouts.append(make_layout(model_item, "utility_flex", "Utility Flex", "combi", total=combi_total, economy=combi_total, cargo_factor=1.0, notes="Reduced seating to preserve more mixed payload capability."))
            continue
        if style == "commuter":
            layouts.append(make_layout(model_item, "single_class", "Single Class", "single_class", total=max_pax, economy=max_pax, cargo_factor=0.86, is_default=True, notes="Highest seat-count commuter layout."))
            premium_total = max(max_pax - 2, int(round(max_pax * 0.9)))
            business = min(6, max(2, int(round(premium_total * 0.12))))
            economy = premium_total - business
            layouts.append(make_layout(model_item, "regional_plus", "Regional Plus", "two_class", total=premium_total, business=business, economy=economy, cargo_factor=0.95, notes="Adds a small premium section for higher-yield regional contracts."))
            continue
        if style == "regional":
            layouts.append(make_layout(model_item, "single_class", "Single Class", "single_class", total=max_pax, economy=max_pax, cargo_factor=0.85, is_default=True, notes="Highest seat-count regional layout."))
            two_class_total = max(max_pax - 6, int(round(max_pax * 0.9)))
            business = max(6, int(round(two_class_total * 0.12)))
            economy = two_class_total - business
            layouts.append(make_layout(model_item, "two_class", "Two Class", "two_class", total=two_class_total, business=business, economy=economy, cargo_factor=0.95, notes="Adds a business section for higher-yield scheduled flying."))
            if bool(model_item.get("combi_capable", False)):
                combi_total = max(18, int(round(max_pax * 0.65)))
                layouts.append(make_layout(model_item, "cargo_flex", "Cargo Flex", "combi", total=combi_total, economy=combi_total, cargo_factor=1.0, notes="Reduced seat count to preserve more mixed passenger and freight capacity."))
            continue
        if style == "regional_jet":
            layouts.append(make_layout(model_item, "single_class", "Single Class", "single_class", total=max_pax, economy=max_pax, cargo_factor=0.84, is_default=True, notes="Highest seat-count regional jet layout."))
            two_class_total = max(max_pax - 8, int(round(max_pax * 0.9)))
            business = max(8, int(round(two_class_total * 0.14)))
            economy = two_class_total - business
            layouts.append(make_layout(model_item, "two_class", "Two Class", "two_class", total=two_class_total, business=business, economy=economy, cargo_factor=0.94, notes="Adds a business cabin for premium regional service."))
            continue
        if style == "narrowbody":
            layouts.append(make_layout(model_item, "high_density", "High Density", "single_class", total=max_pax, economy=max_pax, cargo_factor=0.82, is_default=True, notes="Highest seat-count narrowbody layout."))
            two_class_total = max(max_pax - 18, int(round(max_pax * 0.9)))
            business = max(12, int(round(two_class_total * 0.12)))
            economy = two_class_total - business
            layouts.append(make_layout(model_item, "two_class", "Two Class", "two_class", total=two_class_total, business=business, economy=economy, cargo_factor=0.92, notes="Standard business-plus-economy network layout."))
            premium_total = max(max_pax - 34, int(round(max_pax * 0.82)))
            first = 8 if max_pax >= 180 else 0
            business = 24 if max_pax >= 180 else 16
            premium = 12 if max_pax >= 180 else 0
            economy = max(0, premium_total - first - business - premium)
            layouts.append(make_layout(model_item, "premium", "Premium", "premium", total=premium_total, first=first, business=business, premium=premium, economy=economy, cargo_factor=1.0, notes="Higher-yield narrowbody configuration with more premium seating."))
            continue
        if style == "widebody":
            layouts.append(make_layout(model_item, "leisure", "Leisure Dense", "single_class", total=max_pax, economy=max_pax, cargo_factor=0.80, is_default=True, notes="Highest seat-count long-haul leisure layout."))
            two_class_total = max(max_pax - 30, int(round(max_pax * 0.88)))
            business = max(28, int(round(two_class_total * 0.12)))
            economy = max(0, two_class_total - business)
            layouts.append(make_layout(model_item, "two_class", "Two Class", "two_class", total=two_class_total, business=business, economy=economy, cargo_factor=0.92, notes="Business-plus-economy network widebody layout."))
            premium_total = max(max_pax - 70, int(round(max_pax * 0.78)))
            first = 10 if max_pax >= 320 else 8
            business = max(32, int(round(premium_total * 0.14)))
            premium = max(18, int(round(premium_total * 0.08)))
            economy = max(0, premium_total - first - business - premium)
            layouts.append(make_layout(model_item, "longhaul_premium", "Long-Haul Premium", "premium", total=premium_total, first=first, business=business, premium=premium, economy=economy, cargo_factor=1.0, notes="Higher-yield intercontinental configuration with first, business, and premium economy seats."))
            continue
    return layouts


CABIN_LAYOUTS = build_cabin_layouts(MODELS)
